- .github/workflows/upstream-sync.yaml
- scripts/python-format.sh
This need two reference to be setup on the repository:
- `prev_upstream` a tag initially set to the diverging point between Klipper3d and danger-klipper
- `upstream` the branch on which the reformatted upstream commit will be added on top.
The action will  format each commit in the range `prev_upstream..klipper3d/master` and rebase on top of `upstream`. Then it copies the `upstream` branch to `upstream_pr` and makes a PR with it. The copies allows to resolve conflicts without editing the `upstream` (which should be protected)
Ideally, `upstream` should contain a formatting commit shared with danger's master. However, this is not possible without [rebasing the master branch](https://github.com/Piezoid/klipper/commits/danger_rebased) because the formatting commits are spread-out and …
> Gtihub action syncing with upstream

- docs/G-Codes.md
- klippy/extras/heaters.py
Upstreamed a patch we have internally that allows you to modify your PID parameters without reloading your config. This is useful to work around the current PID implementation in klipper when manually tuning.
> Add ability to modify PID parameters without a reload

- config/printer-artillery-sidewinder-x2-2022.cfg
- config/printer-geeetech-301-2019.cfg
- config/printer-monoprice-select-mini-v2-2018.cfg
- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/fan.py
https://github.com/Klipper3d/klipper/pull/6307
> Kubaracek pwm scaling

- .gitignore
- docs/Config_Reference.md
- klippy/extras/heaters.py
- klippy/extras/pid_calibrate.py
upstream PR: https://github.com/Klipper3d/klipper/pull/6272
> Dans98 klipper velocity pid

- docs/Config_Reference.md
- docs/Dockable_Probe.md
- docs/G-Codes.md
- docs/Status_Reference.md
- klippy/extras/dockable_probe.py
annexed_probe: added dock_retries configuration option
annexed_probe: renamed decouple_speed to detach_speed for consistency
Annexed_Probe.md: initial commit of documentation
Config_Reference.md: added annexed_probe config section
annexed_probe: retry attempts must be greater than 1
annexed_probe: redefine default speeds
annexed_probe: changed delayed detach to optional
Annexed_Probe.md: added section for delayed_detach option
Annexed_Probe.md: (fixed invalid characters and whitespace errors
Annexed_Probe.md: Added additional documentation and gcode reference
Config_Reference.md: Removed extra spaces for annexed_probe and added allow_delayed_detach parameter
G-Codes.md: added annexed_probe gcode reference
annexed_probe.py: changed initial position execution to after docking completed …
> CloakedCode/Mental Dockable Probe

- scripts/klippy-requirements.txt
I had `jinja2>3` installed so I didn't catch the issue.. `jinja2<3` requires `markupsafe==1.1.1`
> revert markupsafe version

- README.md
- docs/Config_Reference.md
- klippy/extras/temperature_fan.py
closed upstream PR: https://github.com/Klipper3d/klipper/pull/4983
> CF3B5 reverse fan

- README.md
- test/klippy/dockable_probe.cfg
- test/klippy/dockable_probe.test
- test/klippy/fan_pwm_scaling.cfg
- test/klippy/fan_pwm_scaling.test
- test/klippy/fan_reverse.cfg
- test/klippy/fan_reverse.test
- test/klippy/gcode_jinja2_ext_do.cfg
- test/klippy/gcode_jinja2_ext_do.test
- test/klippy/pid_hot_modify.cfg
- test/klippy/pid_hot_modify.test
- test/klippy/probe_drop_first_result.cfg
- test/klippy/probe_drop_first_result.test
adding basic tests for features that we have already merged
> tests for danger features

- README.md
- docs/Config_Reference.md
- klippy/extras/display/menu.py
- klippy/extras/virtual_sdcard.py
- test/klippy/virtual_sdcard.cfg
- test/klippy/virtual_sdcard.test
https://github.com/Klipper3d/klipper/pull/6327
> pOmelchenko - virtual_sdcard: add support subdirectories in menu and M'commands

- README.md
- docs/Config_Reference.md
- klippy/extras/danger_options.py
- klippy/mcu.py
- test/klippy/danger_options.cfg
https://github.com/DangerKlippers/danger-klipper/issues/88
> expose the multi mcu homing timeout as a parameter

- README.md
- docs/Config_Reference.md
- klippy/extras/temperature_mcu.py
This allows for boards that don't run their ADC with 3.3V to output accurate MCU temperature readings.
This was originally posted in https://github.com/Klipper3d/klipper/pull/5713 but was rejected by mainline.
The code was written by iKirin of Annex Engineering. With his permission, I've cleaned it up a bit, added a few missing cases and formatted it with Black.
The use case for this is especially rp2040 boards with accurate ADC references. Because of how the Pico board is set up, getting a stable reference is only possible by pulling the reference down to 3.0V. Without this patch, a 3.3V reference is assumed.
> temperature_mcu: add reference_voltage

- klippy/extras/homing.py
- klippy/stepper.py
current helpers was being initialized at stepper init, and at that point all the current helpers haven't been inited yet. delay the assignment of current helper list
> Sensorless dwell bug

- klippy/extras/dockable_probe.py
- klippy/extras/homing.py
original fix: https://github.com/Klipper3d/klipper/pull/4328#issuecomment-1476612792
> dockable_probe: fix bug generating config

- README.md
- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/resonance_tester.py
- klippy/kinematics/limited_cartesian.py
- klippy/kinematics/limited_corexy.py
- klippy/toolhead.py
- scripts/motan/analyzers.py
- test/klippy/limited_cartesian.cfg
- test/klippy/limited_cartesian.test
- test/klippy/limited_corexy.cfg
- test/klippy/limited_corexy.test
I'll copy the relevant parts from the [Discourse thread](https://klipper.discourse.group/t/independant-acceleration-limits-for-x-and-y-axes/3831).
I've been using different accelerations and velocities limits for X and Y on my E3Pro for the past two years. Now that the code has been tested a bit by the community, I decided to share it here.
The syntax for the axis limits are similar to the ones for Z, `max_x_accel`, `max_x_velocity`, etc.
To get all the speedup benefits, main `max_accel` and `max_velocity` should be set to the hypotenuse: √(x²+y²). There is a new gcode command `SET_KINEMATICS_LIMIT` which will show these values and at the diagonal angle where they are reached.
If you set accelerations per feature type in the slicer, and have tuned your acceleration to get similar …
> Independent X & Y Accelerations

- README.md
- docs/Config_Reference.md
- klippy/chelper/kin_extruder.c
- klippy/extras/danger_options.py
- klippy/kinematics/extruder.py
- test/klippy/extruders.cfg
basically a flag to revert https://github.com/Klipper3d/klipper/commit/29724a7411063879d3343a0610b4f288e045cabf and allow pressure advance to come through trapq
should resolve https://github.com/Klipper3d/klipper/issues/6338
in theory, the change in https://github.com/Klipper3d/klipper/commit/29724a7411063879d3343a0610b4f288e045cabf can introduce about 250ms of lag after changing pressure advance, which can reduce performance when printing very fast and frequently changing pressure advance while printing (ie variable pressure advance in role-based gcode)
to enable, add to [extruder]:
`per_move_pressure_advance: True`
> per_move_pressure_advance extruder flag

- README.md
- docs/Config_Reference.md
- klippy/extras/force_move.py
- klippy/klippy.py
adding [force_move] every time you start a config is annoying and there's very little downside to having it on.
let's just load it no matter what (and default it to on)
> load force move and enable it by default

- README.md
- klippy/clocksync.py
- klippy/mcu.py
- klippy/serialhdl.py
add support for hotplugging mcus
> noncritical mcus

- klippy/extras/bed_mesh.py
Update to latest [Klipper3d/klipper](http://github.com/Klipper3d/klipper) (9f41f53c) (Jan 27)
Do not merge from Github, fast-forward locally once the PR is approved.
This small update  contains the bed mesh fixes from  Klipper3d/klipper#6473
> update to latest Klipper3d/klipper (9f41f53c)

- README.md
- docs/Config_Reference.md
- klippy/extras/bed_mesh.py
See issue https://github.com/DangerKlippers/danger-klipper/issues/139
Behavior is as follows:
If bed_mesh_default is not defined, do nothing. If it is, continue.
If the requested mesh is not in the list of meshes, raise warning. If it is, load it.
> add bed_mesh_default option to config

- klippy/kinematics/cartesian.py
- klippy/kinematics/corexy.py
- klippy/kinematics/corexz.py
- klippy/kinematics/delta.py
- klippy/kinematics/deltesian.py
- klippy/kinematics/hybrid_corexy.py
- klippy/kinematics/hybrid_corexz.py
- klippy/kinematics/limited_cartesian.py
- klippy/kinematics/limited_corexy.py
- klippy/kinematics/none.py
- klippy/kinematics/polar.py
- klippy/kinematics/rotary_delta.py
- klippy/kinematics/winch.py
- klippy/toolhead.py
#115
Added explicit flags in each kinematic type for dual carriage support.
Added check in toolhead.py for:
If config contains dual_carriage AND its not supported, throw error.
> added dual_carriage warning

- klippy/extras/temperature_fan.py
This fixes that `temperature_fan` with `control: watermark` never turns off when reverse is set to `False` (the default value).
> temperature_fan: fix fan never turning off when not reversed

- README.md
- docs/Config_Reference.md
- klippy/configfile.py
- klippy/extras/danger_options.py
- test/klippy/danger_options.cfg
Proceeding under my own merits for #151, regarding #149
This update provides two changes to how autosave data is handled via klipper. The first is that included configs are now updated properly. In order to do this, the second change, a dedicated backups directory has been introduced; the importance of which is covered in further detail below. The backups directory will be created in the default configs directory for the printer.
The choice to make autosaving `include`s the danger option rather than the alternate backups directory is two-fold. Changing the path that a backup is saved to won't have any negative impact given that the path is pulled from klippy itself, then appended with the directory name. Additionally, code complexity and failure risk were considered for both options.
I've …
> Changed SAVE_CONFIG to update include configs

- README.md
- docs/G-Codes.md
- klippy/extras/heaters.py
- klippy/extras/pid_calibrate.py
- test/klippy/pid_profile.cfg
- test/klippy/pid_profile.test
It took me quite some time but I had to refine some stuff, smooth out switching between profiles and so on.
Code is working perfectly fine in my fork, though I might have missed something while transfering it so it should be tested (unfortunately I can't really test it since I would have to redo a whole printer as all my printers are running my fork)
Luckily @dans98 offered to test it so there's that
> PID-Profiles

- README.md
- docs/G-Codes.md
- klippy/extras/heaters.py
- klippy/extras/pid_calibrate.py
- test/klippy/pid_profile.cfg
- test/klippy/pid_profile.test
* PID-Profiles
* added documentation
* I forgot to add
* Black formatting
* adding pid_profile tests
* Fixed Remove_Profile
* Updated doc
* Small fix to doc
* readme changes
---------
> pid-profiles v2

- klippy/extras/firmware_retraction.py
- scripts/motan/analyzers.py
This little PR allows you to register commands during initialization. 
Commands must be registered before ``klippy:connect`` to be rewritten by ``gcode_macro.py``.
> fix Commands register to allow override by macros

- klippy/extras/dockable_probe.py
Looks like DK is missing commit [ce73f72](https://github.com/cloakedcode/klipper/commit/ce73f72cab30035b3fb269822fd515bf79a03fff) from its copy of `dockable_probe.py`. This causes a breakage when homing with a dockable_probe + virtual z endstop + safe_z_home. When homing z, I get this error:
```
Must home axis first: 125.000 125.000 20.705 [0.000]
```
The same happens with the hacky z-hop I had in my own [homing_override](https://github.com/timwu/trident_configs/blob/main/sensorless-homing.cfg#L18-L54).
Merging in the commit seems to fix my issue with `safe_z_home` and my `homing_override`.
> fix homing error with dockable_probe and safe_z_home

- klippy/extras/adxl345.py
- klippy/extras/angle.py
- klippy/extras/bus.py
- klippy/extras/lis2dw.py
- klippy/extras/mcp4018.py
- klippy/extras/samd_sercom.py
- klippy/extras/tmc_uart.py
- klippy/mcu.py
- klippy/serialhdl.py
most klipper mcus weren't correctly reconnecting, this fixes
klipper extras mcu configuration pattern is that we should call mcu.add_config_cmd from the config callback. we didn't do that for most extras which caused issues. this moves the add_config_cmd calls from the `__init__` to the config callback for all extras
> move add_config_cmd calls to config callback across all extras

- klippy/extras/z_calibration.py
With dockable_probe, when auto_attach_detach == true, the probe is detached during Calibrate_Z after first probe
Adding multi_probe_begin() / multi_probe_end(), no need to configure start_gode, end_gcode with dockable_probe if auto_attach_detach is true.
> Fix behavior of z_calibration with dockable_probe

- docs/Config_Reference.md
- klippy/extras/danger_options.py
- klippy/toolhead.py
- test/klippy/danger_options.cfg
This https://github.com/DangerKlippers/danger-klipper/commit/7a74888b43a7e640a32fd18ae69d9dbdeaf55719 adds an extra flush time 0.25s. In certain conditions it will result in homing/probing latencies. 
Proposal to make it configurable.
> Makes BGFLUSH_EXTRA_TIME configurable

- README.md
- klippy/extras/heaters.py
- klippy/mcu.py
> adc out of range: expose heater thermistor out of min/max

- README.md
- klippy/klippy.py
- klippy/queuelogger.py
To use this, edit the file `~/printer_data/systemd/klipper.env` and append `--rotate-log-at-restart` to the `KLIPPER_ARGS` variable.
E.g.:
```bash
$ cat /home/pi/printer_data/systemd/klipper.env
KLIPPER_ARGS="/home/pi/klipper/klippy/klippy.py /home/pi/printer_data/config/printer.cfg -I /home/pi/printer_data/comms/klippy.serial -l /home/pi/printer_data/logs/klippy.log -a /home/pi/printer_data/comms/klippy.sock --rotate-log-at-restart"
```
> core: rotate log file at every restart

- README.md
- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/filament_motion_sensor.py
- klippy/extras/filament_switch_sensor.py
Added a runout_distance parameter to filament switch sensors which means that after a filament_switch sensor triggers the printer will print for another `x` mm of filament (if your sensor sits at the end of a reverse bowden tube)
Filament sensor parameters can now be set via command (If you run a reverse bowden between motion sensor and extruder and retract after a print, there will be a buffer in the bowden which means you intially need a higher detection length than you would need while printint, now you can adjust it on the fly)
Added smart parameter to the sensors:
normally the sensor class uses the idle_timeout sttatus to determine whether the printer is printing, which also tiggers of you just move the toolhead (leading to false positives)
if smart is set to 1, it will use the …
> filament_switch_sensor: runout distance, smart and runout gcode

- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Status_Reference.md
- klippy/extras/belay.py
This adds the `belay` module from the [Annex Belay repo](https://github.com/Annex-Engineering/Belay) and copies related documentation into the following documents:
- Config_Reference
- G-Codes
- Status_Reference
> Add belay module

- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Status_Reference.md
- klippy/extras/trad_rack.py
This adds the `trad_rack` module from the [Annex TradRack repo](https://github.com/Annex-Engineering/TradRack) and copies related documentation into the following documents:
- Config_Reference
- G-Codes
- Status_Reference
The [trad_rack] sections in the documents listed above currently contain links to other documents in the TradRack repo (I left those as is for now). Let me know if you would rather I copy those other documents into a separate file in the DangerKlipper docs folder so the links will point to that file instead or if I should remove those links.
> Add trad_rack module

- klippy/configfile.py
- klippy/extras/adc_temperature.py
- klippy/extras/bed_mesh.py
- klippy/extras/danger_options.py
- klippy/extras/homing.py
- klippy/extras/statistics.py
- klippy/klippy.py
- klippy/mcu.py
- klippy/serialhdl.py
- klippy/toolhead.py
- klippy/webhooks.py
instead of using printer.lookup_object, now you can just import `get_danger_options` from `danger_options.py`
> Danger Options interface rework + new logging flags

- .flake8
- klippy/extras/adxl345.py
- klippy/extras/danger_options.py
- klippy/extras/display/display.py
- klippy/extras/display/st7920.py
- klippy/extras/display/uc1701.py
- klippy/extras/neopixel.py
- klippy/extras/temperature_mcu.py
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc_uart.py
- klippy/mcu.py
- klippy/serialhdl.py
- klippy/stepper.py
oids and config commands can/will be created either from module `__inits__` or from config callbacks. At a reconnect, the module inits will not be called again, but the config callbacks will be. 
the approach implemented here is to cache the oid_count and config / init / restart commands before we call the callbacks for the first time. this way, we know the state of the oids and command lists that we need to return to before calling the callbacks. this way, the oids and commands should all end up correct.
additionally, we emit two events for noncritical reconnect / disconnects that modules can subscribe to for handling state management across disconnects / reconnects
> Non-critical MCUs re-work

- README.md
- docs/G-Codes.md
- klippy/extras/heaters.py
- klippy/gcode.py
- klippy/klippy.py
adds a gcode command: `HEATER_INTERRUPT`
also allows any command with `INTERRUPT` in it to skip mutex
> gcode interrupts

- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/filament_motion_sensor.py
- klippy/extras/filament_switch_sensor.py
As discussed in the DK Discord channel
> Fixed issues with HappyHare

- klippy/extras/temperature_fan.py
- klippy/extras/temperature_sensor.py
- klippy/mcu.py
well title says it all
And thermocouples will be exposed as well
> Also expose temperature_fan and temperature_sensor

- README.md
- docs/Config_Reference.md
- klippy/configfile.py
- test/klippy/recursive_globs.cfg
- test/klippy/recursive_globs.test
- test/klippy/recursive_globs_include/recursive_globs.include
- test/klippy/recursive_globs_include/recursive_globs_include.cfg
https://github.com/Klipper3d/klipper/pull/6375
Basically says it all
- [ x] pr title makes sense
- [ x] added a test case if possible
- [ x] if new feature, added to the readme
> Use recursive globs to include config files

- klippy/extras/resonance_tester.py
> hotfix: disable min_cruise_ratio correctly

- docs/Config_Reference.md
- docs/Dockable_Probe.md
- klippy/extras/dockable_probe.py
- test/klippy/dockable_probe.cfg
Just adding some improvements to dockable_probe:
- `restore_toolhead` : if true move back to the position prior attach/detach, if false : no moves.
- `extract_position` , `insert_position` : optional positions for Euclid style probes, no need command overrides
- expose `auto_attach_detach` value
I did my best with py format and doc. :/
I just tested with Euclid and klicky on a 2.4, probably need more feedbacks
> Some improvements to dockable_probe

- klippy/extras/dockable_probe.py
```
File "/home/cime/klipper/klippy/extras/probe.py", line 157, in _probe
epos = self.mcu_probe.probing_move(pos, speed)
AttributeError: 'DockableProbe' object has no attribute 'probing_move'
MCU 'can0' shutdown: Command request
```
due to https://github.com/DangerKlippers/danger-klipper/commit/acdf8bb1080ab829c6e8092dadf6d488aa416f77
> dockable_probe: def probing_move()

- klippy/extras/dockable_probe.py
While ``restore_toolhead : false``, PROBE_ACCURACY occurs at extract_position.
> dockable_probe: fix PROBE_ACCURACY position while restore_toolhead=false

- README.md
- docs/Config_Reference.md
- klippy/extras/temperature_fan.py
- test/klippy/curve_control.cfg
- test/klippy/curve_control.test
Add another control algorithm to a temperature fan called curve.
It's basically the same thing you use in your pc, you jsut define a temperature curve and off you go.
Should be pretty self explanatory but please let me know if my documentation makes sense to you :)
Feedback is welcome as always
> Curve Fan Control

- klippy/extras/homing.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2240.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
When utilizing home_current + sensorless homing the run_current is not being restored after homing was completed.
- The needs_home_current_change check will be fales because run_current at that time is equal to home_current
- The short circuit code in most drivers is triggering falsely because it's comparing the previous run current to the requested run_current and not looking at the currently set run current, thus never setting this even after switch to a `needs_run_current_change` helper in the condition.
> bugfix: restore run_current after sensorless homing

- docs/Config_Reference.md
- klippy/extras/bme280.py
Extends the BMxx80 category with support for the BMP388 sensor, providing temperature and pressure output similar to the existing BMxx80 class of sensors.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6576
> bme280: Add BMP388 sensor support to BMxx80 (#6576)

- klippy/mcu.py
bug in mcu.py wasn't invoking `get_danger_options` function
> invoke danger options when checking adc ignore limits

- docs/Measuring_Resonances.md
Current command, using the *, results in bad chart output when more than one .csv file exists in the tmp folder. This isn't obvious for people who may not know that the * is a wildcard character.
Klipper PR:  https://github.com/Klipper3d/klipper/pull/6509
> docs: Update Measuring_Resonances.md (#6509)

- klippy/configfile.py
- klippy/serialhdl.py
logging.warn is an alias to logging.warning since Python 3.3 and will be removed in Python 3.13.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6580
> klippy: Replace logging.warn usage with logging.warning (#6580)

- docs/Status_Reference.md
Add gcode_button to the Status Reference docs
Klipper PR: https://github.com/Klipper3d/klipper/pull/6201
> docs: Add gcode_button to the Status Reference docs (#6201)

- src/stm32/Kconfig
- src/stm32/fdcan.c
- src/stm32/stm32g4.c
- src/stm32/stm32h7_adc.c
- test/configs/stm32g474.config
stm32: Add STM32G474 chip to Kconfig
stm32: Add FDCAN2 channel needed for stm32g4 alternate pins
stm32g4: Fix ADC3 common interface registers name to ADC345_COMMON
Klipper PR: https://github.com/Klipper3d/klipper/pull/6585
> STM32 module fixes to support Stm32g474 with FDCAN (#6585)

- klippy/mcu.py
beacon (and maybe others) loads a temperature sensor but doesn't define `is_adc_faulty()`
> mcu: validate if heater/sensor has is_adc_faulty()

- klippy/kinematics/cartesian.py
- klippy/kinematics/hybrid_corexy.py
- klippy/kinematics/hybrid_corexz.py
- klippy/kinematics/idex_modes.py
idex_mode would swap the X and dual-carriage rail in some cases (homing), but not in others. As such, the position calculation was correct while homing, but incorrect for the second carriage during normal moves. This commit fixes homing to work without swapped rails, removes the swapping of rails while homing, and removes the ability to swap rails (as it is now no longer used). Fix has been tested in a Hybrid_CoreXY IDEX printer (Voron Double Dragon). Hybrid_CoreXZ has identical changes and is similar enough that I am confident it will work as intended. Changes to cartesion seem simple enough, but would benefit from someone running a couple of tests.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6486
> idex_modes: Bugfix for kinematic position calculation.

- klippy/extras/bed_mesh.py
Round beds require an odd number of probe points in order to prevent erroneously truncating the mesh.
The adaptive mesh algorithm did not consider that and as a result, it was possible to generate adaptive
meshes with even number of probe points.
This change fixes this by increasing the probe point count by 1 in cases where the adaptive probe points are even.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6600
> bed_mesh: Fix adaptive probe count on delta printers (#6600)

- .flake8
- README.md
- klippy/clocksync.py
- klippy/extras/adxl345.py
- klippy/extras/danger_options.py
- klippy/extras/display/display.py
- klippy/extras/display/st7920.py
- klippy/extras/display/uc1701.py
- klippy/extras/neopixel.py
- klippy/extras/temperature_mcu.py
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc_uart.py
- klippy/mcu.py
- klippy/serialhdl.py
- klippy/stepper.py
adds non-critical-mcus to bleeding-edge-v2
> non critical mcus v2

- klippy/chelper/integrate.c
- klippy/chelper/integrate.h
- klippy/chelper/kin_extruder.c
- klippy/chelper/kin_shaper.c
https://github.com/DangerKlippers/danger-klipper/issues/207
This eliminates extrusion errors (retraction issues, corner distortions, etc.) caused by applying the smoothing kernel to the base E position, which is not needed for or motivated by the pressure advance model.
Fixes Danger Klipper issue 207 / upstream Klipper issue 4442.
Since the base position integrator is also used by changes to kin_shaper for "input smoothing", that functionality is left in place, but without the integration of the velocity term (the part needed for PA) which is moved to its own function.
> pressure advance: do not smooth base extruder position, only advance

- klippy/extras/homing.py
- klippy/extras/tmc.py
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2209.py
- klippy/extras/tmc2240.py
- klippy/extras/tmc2660.py
- klippy/extras/tmc5160.py
bugfix sensorless not returning to run_current after homing
I also took the opportunity to start a new BaseTMCCurrentHelper() class to reduce the duplicated code and added comments to the code to help people working on it in the future.
> bugfix sensorless not returning to run_current after homing

- klippy/extras/heaters.py
Change filament defaults to density=1.2 and specific heat=1.8. Based on a review of filament properties this should be good defaults to allow filament feed forward to work well for most users out of the box.
MPC doc, currently in PR, will be updated to reflect these default values (https://github.com/DangerKlippers/danger-klipper/pull/275)_
- [X ] pr title makes sense
- [ X] squashed to 1 commit
- [ N/A] added a test case if possible
- [ X] if new feature, added to the readme
- [ N/A] ci is happy and green
> Update heaters.py, on mpc_experimental, to include reasonable default filament values

- klippy/extras/tmc2240.py
- klippy/extras/tmc5160.py
Correct the name of "cs_actual" and correct the size on tmc5160.
https://github.com/Klipper3d/klipper/commit/b6a0063235dd58bc9c1bb5767e87e09c9927f39a
> tmc5160: csactual -> cs_actual

- klippy/webhooks.py
- scripts/buildcommands.py
This will help frontends (Fluidd/Mainsail) validate whether the user is running Danger-Klipper or native Klipper.
`_handle_info_request()` response is rendered raw to Moonraker's `/printer/info`, so no changes to Moonraker are needed.
I also took the opportunity to rename the MCU data dict for firmware builds.
> core: expose danger-klipper to moonraker

- scripts/klippy-requirements.txt
we don't support python2, and thats the reason those are pinned to old versions
python-can/pyserial you are the next 💯
> bump jinja2 and markupsafe versions

- klippy/extras/resonance_tester.py
- klippy/extras/shaper_calibrate.py
- scripts/calibrate_shaper.py
https://github.com/DangerKlippers/danger-klipper/issues/221
> shaper_calibrate: store accel_per_hz

- docs/MPC.md
I added an example macro to the documentation. Enjoy
> Add an example macro for auto-configuring MPC material properties

- klippy/console.py
- klippy/mcu.py
- klippy/msgproto.py
That's a continuation of https://github.com/DangerKlippers/danger-klipper/pull/285, but now for mcus
UIs now can show if MCUs are running Danger-Klipper or Klipper with no modifications required to Moonraker
> mcu: expose the mcu app name to mcu.get_status and logs

- klippy/extras/homing.py
Instead of sleeping for every stepper change, do it once after changing them all
It also consolidates the current change method to avoid a bit of duplicated code
> sensorless: dwell once for all rails

- klippy/extras/homing.py
- klippy/extras/tmc.py
I introduced a bug in https://github.com/DangerKlippers/danger-klipper/pull/298. 
`_set_current_homing` and `_set_current_post_homing` were consolidated into a single method, and I missed the difference between `ch.needs_home_current_change` and `ch.needs_run_current_change`.
A new method, `ch.needs_running_current_change`, now validates if any running current needs changing.
> bugfix: sensorless return to run current

- klippy/clocksync.py
- klippy/extras/spi_temperature.py
The problem is outlined in https://github.com/Klipper3d/klipper/issues/6619
In this PR, I have done two things:
- Add a simple check to avoid reporting the wrong temperature
- Add some warnings for when an uncompleted clock sync is used in `clock_to_print_time()` and `print_time_to_clock()`
There may be a better solution to this; I'm not sure. I headed down the path of making `clock_to_print_time()` and `print_time_to_clock()` raise an exception, but there's just too much stuff that happily accepts the wrong value for my little non-python-fluent brain to handle it all.
> Don't use incomplete clock sync for SPI temperature; always warn

- README.md
- docs/Danger_Features.md
- docs/G-Codes.md
- klippy/configfile.py
- klippy/console.py
- klippy/extras/gcode_macro.py
- test/klippy/gcode_jinja2_ext_do.test
new RELOAD_GCODE_MACROS g-code command to reload gcode_macro templates without a firmware restart
> gcode_macro: adds RELOAD_GCODE_MACROS

- klippy/extras/control_mpc.py
- klippy/klippy.py
This is a change to MPC to make the ambient heat loss actually make sense. See examples.
Command: MPC_CALIBRATE HEATER=extruder TARGET=230
Done on an Ender 3 V2 Neo with 40 Watt heating element, copper heat block.
Original:
0% fan average power: 21.81 W
50% fan average power: 20.74 W
100% fan average power: 21.01 W
0.1 temperature target:
0% fan average power: 20.86 W
50% fan average power: 20.68 W
100% fan average power: 20.50 W
heat soak and stabilization:
0% fan average power: 20.65 W
50% fan average power: 20.61 W
100% fan average power: 21.53 W
0.1 target, heat soak and stabilization:
0% fan average power: 20.23 W
50% fan average power: 21.01 W
100% fan average power: 21.97 W
The 0.1 degree target method was better in some ways but it did not have the desired effect. That is because …
> MPC: Increase accuracy

- README.md
- docs/G-Codes.md
- klippy/extras/resonance_tester.py
as suggested by @lhndo in https://github.com/DangerKlippers/danger-klipper/issues/295, it complements https://github.com/DangerKlippers/danger-klipper/pull/224 and allows the user to try different accel_per_hz without having to edit the config and restart the firmware.
> feat/resonance_tester: accepts ACCEL_PER_HZ in TEST_RESONANCES

- klippy/extras/heaters.py
As reported in a Discord help thread, the feature that reports faulty heaters is throwing an error if the heater was a prefixed one (e.g., generic_heater). The reason is that `pheaters.available_heaters` returns the full object name, including the prefix, but `pheaters.lookup_heater` doesn't accept that. 
instead of splitting the name there, I preferred to modify `lookup_heater` to improve future uses of it. 
> bugfix/heaters: auto detect generic heaters when looking up heater objects

- klippy/extras/fan.py
- test/klippy/fan_pwm_scaling.cfg
As reported in https://github.com/DangerKlippers/danger-klipper/issues/290, the config below throws an error because we are trying to min() between `max_power` and `shutdown_speed`.
```
[fan]
max_power: 0.95
shutdown_speed: 1
hardware_pwm: False (default)
```
> bugfix/fan: shutdown shouldnt use max_power when hardware pwm is not set

- klippy/extras/dockable_probe.py
According to this issue https://github.com/DangerKlippers/danger-klipper/issues/322,  when the `safe_dock_distance` is zero _move_avoiding_dock may not correctly calculate an exit point. This PR disables the avoidance function in this situation.
> Dockable_probe : Fix _move_avoiding_dock if no safe_area

- scripts/motan/readlog.py
The mcu_phase_offset should be added not subtracted.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6612
and ruff fixes
> motan: Fix logic error resulting in incorrect stepper phase graphing (#6612)

- klippy/extras/tmc2130.py
- klippy/extras/tmc5160.py
https://github.com/DangerKlippers/danger-klipper/issues/325
We want to make sense_resistor mandatory in the future, but let's warn it first and avoid breaking existing configs.
> feat/tmc - warning for sense_resistor

- klippy/klippy.py
Make the user-plugins system work with plugins that come as a package, for example the Klipper Shake&Tune plugin.
Testing: Installed Shake&Tune, move the directory from `extras/` to `plugins/`. Without the fix the plugin could no longer be found.
```bash
pi@uku:~/klipper/klippy $ ls -laR plugins/shaketune/
plugins/shaketune/:
total 56
drwxr-xr-x 6 pi pi 4096 Jul 29 20:53 .
drwxr-xr-x 7 pi pi 4096 Jul 29 20:53 ..
drwxr-xr-x 3 pi pi 4096 Jul 29 20:53 commands
-rw-r--r-- 1 pi pi 4245 Jun 19 19:15 dummy_macros.cfg
drwxr-xr-x 3 pi pi 4096 Jul 29 20:53 graph_creators
drwxr-xr-x 3 pi pi 4096 Jun 19 19:23 helpers
-rw-r--r-- 1 pi pi  766 Jun 14 21:58 __init__.py
drwxr-xr-x 2 pi pi 4096 Jul 29 20:53 __pycache__
-rw-r--r-- 1 pi pi 2424 Jun 14 21:58 shaketune_config.py
-rw-r--r-- 1 pi pi 4403 Jun 19 …
```
> bugfix: Make user-plugins work with package directories

- docs/MPC.md
Big re-format and update to the MPC documentation to support MPC feature release to mainline in PR https://github.com/DangerKlippers/danger-klipper/pull/333. Primary focus was to bring the overall content format inline with other documents and make setup and configuration clear and concise. Feedback from the beta was integrated to support common issues and questions. Bed setup was moved to experimental section to help clarify that currently MPC is primary intended to be used with the extruder heater. No significant content removals IMO.
The following areas were added:
- PTC temp-heater chart
- Note on overshoot / undershoot and how MPC controls block temp and not sensor temp.
- Temp wait macro
As with all documentation updates, I welcome review and feedback.
- [X ] pr title makes sense
- …
> MPC doc update to support PR#333

- README.md
- docs/Config_Reference.md
- docs/Danger_Features.md
- klippy/extras/control_mpc.py
- klippy/extras/heaters.py
- klippy/klippy.py
- test/klippy/mpc.cfg
- test/klippy/mpc.test
This adds MPC control law to main branch.
Has been extensively tested on `feature/mpc_experimental` branch but would like to get to main so we can get wider testing. Would appreciate final code review.
Let me know if we need to add any extra docs.
Best regards,
Lasse
> control_mpc: add MPC control law

- README.md
- docs/Config_Reference.md
- docs/Danger_Features.md
- klippy/extras/probe.py
- klippy/extras/z_tilt.py
- klippy/extras/z_tilt_ng.py
Adaptive horizontal move z option for probe helper
> adaptive horizontal move z

- klippy/extras/z_tilt.py
- klippy/extras/z_tilt_ng.py
```python
>>> done2
'done'
>>> (done2 and int(done2) == 0) or done2 == "done"
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'done'
```
> bugfix/z_tilt: check if retry_result is a number before converting

- docs/MPC.md
Fixed what looks like a typo in the MPC docs
> Replaced default filament_diameter value with 1.75 in MPC docs

- src/stm32/stm32h7_adc.c
* Fix getting wrong ADC value on PA0
* Fix invalid/unused pin being used as adc channel on STM32H7/G431/L4
Klipper PR: https://github.com/Klipper3d/klipper/pull/6660
> stm32: Fix getting wrong ADC value on PA0 of STM32G431 (#6660)

- klippy/extras/servo.py
This change follows the same approach as implemented for fan control. The change removes the move queue flushing when changing servo position, which does not appear to be necessary. This can be beneficial, for example, for WS7040-based cooling on IDEX setups where the servo can be used to control the air flow between the toolheads, with this change eliminating micro-stutters of the toolhead on servo position adjustment.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6656
> servo: Asynchronous adjustments of servo position

- klippy/kinematics/idex_modes.py
- test/klippy/dual_carriage.cfg
- test/klippy/dual_carriage.test
Previous implementation could crash the idex carriages into each other. The new code moves the idex carriages together, eliminating this risk and decreasing the time needed to restore the carriages positions.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6653
> idex_modes: Improved restoring position in RESTORE_DUAL_CARRIAGE_STATE

- klippy/extras/smart_effector.py
- klippy/gcode.py
- src/stm32/stm32g4.c
- src/stm32/stm32l4.c
- stm32: Fix setting USB clock with USB to CANbus mode on stm32g4/stm32l4
- gcode: Minor change to suppress python warning on '\s'
- smart_effector: Define get_position_endstop() wrapper
> mainline commits sync

- scripts/spi_flash/board_defs.py
Klipper PR: https://github.com/Klipper3d/klipper/pull/6646
> spi_flash: Add stm32g0b0xx to board_defs.py (#6646)

- Makefile
`make KCONFIG_CONFIG=/path/to/my/.config` currently works, but is verbose and requires every step to have that variable. 
Loading from the environment using `?=` (set if not already) instead of `:=` (simple assignment) allows easier scripting
> Allow overriding the KCONFIG_CONFIG path from environment variables

- README.md
- docs/Command_Templates.md
- klippy/extras/gcode_macro.py
- test/klippy/action_log.cfg
- test/klippy/action_log.test
Small change so there is a action to write something to the log, can be usefull for automated z-offset calculation or other stuff that is usefull to be logged
> action_log

- klippy/extras/smart_effector.py
This reverts commit 82b779a476cd6bf550d6bde53c4544e141f2318e.
https://github.com/DangerKlippers/danger-klipper/issues/363
> Revert "smart_effector: Define get_position_endstop() wrapper"

- klippy/extras/z_tilt_ng.py
This causes klipper to eventually error catastrophically as numpy
infects more and more of the printer status, eventually causing
crashes in webhook.py because json.dumps cannot serialize
numpy values
I verified this worked with a successful Z_TILT_AUTODETECT
> [bug] z_tilt_ng applies numpy float64 values to the toolhead

- src/rp2040/spi.c
The Fysetc PITB V2 board uses a spi bus config that is supported by the RP2040 chip, but not klipper, so this adds the relevant config to the file to allow you to run the tmc5160's on the board via hardware SPI.  This resolves the issue of software spi not working on this board, which I was unable to fully understand.
I have also seen other users encounter similar bus config issues with the rp2040 setting up things like accelerometers and such with this pin layout.
Been running this a few weeks on baseline klipper, but they seem uninterested in my PR (6683) so maybe pitb can be supported here?
> rp2040/spi: Add spi0e bus to support fysetc PITB V2

- docs/Config_Reference.md
- docs/Danger_Features.md
- klippy/extras/safe_z_home.py
- test/klippy/safe_z_home.cfg
- test/klippy/safe_z_home.test
New [safe_z_home] parameter to let you invert the XY homing order. 
The idea is from the `beacon.py` module, so thanks @dalegaard @mattthebaker
> [safe_z_home] - home_y_before_x

- README.md
- docs/Config_Reference.md
- klippy/extras/bltouch.py
- klippy/extras/danger_options.py
- klippy/extras/homing.py
- klippy/klippy.py
Makes the homing constants, 
`HOMING_START_DELAY`, `ENDSTOP_SAMPLE_TIME`, and `ENDSTOP_SAMPLE_COUNT` configurable from danger_options
lowering `ENDSTOP_SAMPLE_COUNT` to 1 should likely resolve some probing drift some users have been observing
> make homing constants configurable

- README.md
The new version has an option to specify the custom repository directly on the menu.
> update install instructions for kiauh v6

- docs/G-Codes.md
- docs/Status_Reference.md
- klippy/extras/trad_rack.py
This change adds various small updates to the trad_rack module:
- Update description for TR_RESUME since it is no longer only used after a failed load or unload: Annex-Engineering/TradRack@f597dab
- Compatibility with changes to PrinterExtruder (from bleeding-edge-v2): #324
- Replace PAUSE_STATE with the pre-toolchange gcode state when pausing due to a failed toolchange: Annex-Engineering/TradRack@47ed7c5
- (ensures RESUME brings the toolhead to the right place when it restores PAUSE_STATE, avoiding an error where the rest of the current layer is printed at the wrong height if the toolhead was moved during the toolchange command and the print file does not contain any z movements until the next layer)
- Make _load_lane() and _load_selector() less redundant: …
> trad_rack: various small updates

- klippy/configfile.py
In order to ensure users don't get confused where an option is
really being set, SAVE_CONFIG currently checks that include
files do not set options that are being saved in the main
config file's autosave section.
However, this means you can't set, say, the control mechanism
for a heater in an include file, because it is also
part of the autosave block.
This commit changes the conflict check to only consider it a
conflict if the included value differs from the one in the
autosave block (so it is okay if both set 'control:mpc' as an
example)
Signed-off-by: Daniel Berlin <dberlin@dberlin.org>
> Don't consider included options conflicting if they are the same value

- klippy/kinematics/delta.py
In current versions of (danger)-klipper, the configured `print_radius` on a delta printer is just silently ignored when it's larger than `arm_length - delta_radius`. 
While points beyond that radius might not be useful for actual print moves, I have a klicky-style probe that I want the printer to pick up outside of the "reasonable" build volume, which was formerly prevented by the above issue.
I tested the committed code on my delta printer and it solves my issue. Additionally I actively tried running it into "unreachable" territory (i.e. to the point where one of the arms would have to be horizontal and the stepper moving at infinite speed, and beyond) and found that klipper safely shuts down, without excessive movement etc.
> Trust the user on the print_radius for delta kinematics

- docs/CANBUS.md
- docs/Danger_Features.md
- scripts/canbus_query.py
- src/generic/canserial.c
msg=[0x00] responds with a klipper-compatible response
- Response is [0x20, canbus_uuid, app_id] (0x01 for klipper, 0x11 for Canboot)
msg=[0x00, 0x01] enables extended responses.
- "Normal" Klipper devices will ignore this extended bit completely
- Danger-Klipper devices will now respond regardless of whether the device is already assigned a node_id. Responses are generally klipper-compatible, although in the odd case that someone manually sends [0x00, 0x01] from Klipper, the app_name will probably show as "Unknown", unless it happens to be 0x01 or 0x11. If the device is already assigned, the response will be ignored completely
- Response: [0x20, canbus_uuid, 0x07] 0x07 being a new Danger-Klipper app_id
- Response: [0x21, canbus_uuid, node_id] 0x21 is a new "RESP_HAVE_NODEID" value
This …
> canbus: Add CMD_QUERY_UNASSIGNED extended response, enabling query response after id assignment

- klippy/extras/z_tilt.py
- klippy/extras/z_tilt_ng.py
> bugfix/retry_result: 0.0 is False

- .github/workflows/ci-static_analysis.yaml
- klippy/configfile.py
- klippy/extras/filament_motion_sensor.py
- klippy/extras/hall_filament_width_sensor.py
- klippy/extras/safe_z_home.py
- klippy/extras/temperature_fan.py
- klippy/kinematics/delta.py
- scripts/requirements_dev.txt
pre-commit runs ruff lint and ruff format checks, but ci only runs lint
> ci: apply ruff format to match precommit

- klippy/mcu.py
This reduces the chance of spurious MCU clock configuration warnings.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6720
> mcu: Only warn about mcu clock frequency if drift is more than 1%

- scripts/flash_usb.py
This solves an issue where the USB directory could exist, but the busnum file itself may not exist immediately. This was encountered when flashing a Pico connected to a Raspberry Pi 5.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6690
> flash_usb: Wait for busnum file to exist when flashing with picoboot (#6690)

- docs/Config_Reference.md
- klippy/extras/ads1220.py
* fix type comparison bug that stopped the sensor from initializing
* correct mismatch between docs and code for `sample_rate` (fixed to work same as hx71x)
* add input_mux, pga_bypass and vref options
* update configuration reference & fix typo
Klipper PR: https://github.com/Klipper3d/klipper/pull/6713
> ads1220: Add input_mux and vref options to ADS1220 sensor (#6713)

- scripts/spi_flash/board_defs.py
- scripts/spi_flash/spi_flash.py
Add flashsd configuration for Tronxy x5sa and other printers based on Chitu v6 board.
These boards should support sdio (this is what the schematic details), however I couldn't get this working from a quick try.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6671
> flashsd: Add support for chitu-v6 (#6671)

- src/avr/timer.c
- src/generic/armcm_timer.c
- src/generic/timer_irq.c
- src/linux/timer.c
- src/sched.c
- src/sched.h
Rename sched_tasks_busy() to sched_check_set_tasks_busy() and change it to only return true if tasks are active (running or requested) for two consecutive calls.  This makes it less likely that timers will yield to tasks except when tasks really are notably backlogged.
This also makes it less likely that multiple steppers controlling the same rail will be interrupted by tasks mid-step.  This should slightly improve the timing, and make it less likely that a halt during homing/probing will occur with these steppers taking a different number of total steps.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6717
> sched: Improve timer vs task priority check

- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/Status_Reference.md
- klippy/extras/fan.py
The current PR :
- reverts and deprecates `speed` fan status to fix UI behavior and not break the API as discuss in https://github.com/fluidd-core/fluidd/issues/1457
- deprecates `off_below` 
- introduces `value` (real speed) and `power` status for future UI devs.
> fan.py : revert speed and deprecate off_below for UI compatibility

- scripts/klippy-requirements.txt
should fix https://github.com/DangerKlippers/danger-klipper/issues/422 and numpy + python3.12
> requirements/bump numpy to latest v1.26

- docs/_klipper3d/mkdocs_hooks.py
Fixes the docs relative links by adding the missing "/" between the repo url and "blob"
Fixes #435
> Fixes docs relative links

- docs/Config_Reference.md
- klippy/extras/fan.py
This property allows fans to have an initial speed on startup, without using delayed G-code.
The benefit is that you don't need delayed G-code anymore and can create fixed-speed `controller_fan`s that can't be controlled through your web interface or commands.
> fan: add initial_speed property

- scripts/canbus_query.py
- src/generic/canserial.c
I was accidentally sending the CanBoot/Katapult app_id 0x11 instead of the Danger app_id 0x07
Additionally, its Katapult now not CanBoot
Fixes #445
> Fix the canserial query response

- docs/Config_Reference.md
- klippy/extras/tmc.py
- klippy/extras/tmc5160.py
At 48v, the default s2vs/s2g_level of 6 is too low in some cases. This can be seen on some large printers where you may get spurious ShortToGround or ShortToSupply
Because s2vs/s2g_level are write-only, we must configure the full register as we can't read the existing values to update. As they are adjustable from OTP, we can't assume a default of `6`, and I don't want to change behavior for existing configurations.
I prefer having the individual fields with the config checks over a single opaque integer value such as `driver_short_conf: 331278` (which sets s2vs and s2g to 12, other values to defaults). 
My future goal is to add a `connect` time hook to tmc driver initialization, allowing reading the OTP_READ values to populate these defaults (Setting the OTP bit `otp_s2_level` raises the …
> Add TMC5160 short_conf configuration

- docs/MPC.md
- klippy/extras/control_mpc.py
This allows for changing your MPC calibration values on the fly.
I need to update my MPC values while docked to offset for what is effectively a heatsink as a nozzle rest.
> Add calibration fields to MPC_SET

- klippy/extras/telemetry.py
- klippy/gcode.py
- klippy/klippy.py
Telemetry is explicitly OPT-IN for privacy concerns
Configuration is semi-anonymized (option values are removed), and no
identifying information besides a machine-unique ID are sent
On startup after updating, a message is sent to the printer console
```
// Welcome to Kalico
// 
// Kalico is starting an opt-in analytics campaign, collecting anonymous data about our users
// Submitted data will contain an anonymized copy of your current configuration, enabled Kalico modules and plugins, and some basic information about the host machine.
// 
// `ENABLE_TELEMETRY` will opt-in to the campaign
// `DISABLE_TELEMETRY` will permanently opt-out
// 
// `TELEMETRY_EXAMPLE` will save a full copy of what would be submitted as 'telemetry.json' in your configuration folder
// 
// For more information, …
```
> Add telemetry module

- docs/Config_Reference.md
- klippy/extras/display/aip31068_spi.py
- klippy/extras/display/display.py
display: Add support for `AIP31068` based displays
Klipper PR: https://github.com/Klipper3d/klipper/pull/6639
> display: Add support for `AIP31068` based displays (#6639)

- klippy/extras/homing.py
- klippy/stepper.py
- src/trsync.c
During a probe attempt, the internal tracking of positions should not change. Verify this after each probe and log a warning if the post-probe position tracking does not match the pre-probe position tracking.
Also, fix an error in the ldc1612 probe trigger notification - it should have called trsync_do_trigger() with irqs disabled. Fix by changing trsync_do_trigger() to internally disable irqs to avoid issues like this in the future.
-Kevin
EDIT: This was discussed at: https://klipper.discourse.group/t/z-stepper-microstep-shift-on-multi-mcu-homing-loadcell-ldc1612/19524/
Klipper PR: https://github.com/Klipper3d/klipper/pull/6718
> Probe position skew warning and ldc1612 irq fix (#6718)

- docs/Config_Reference.md
- docs/Danger_Features.md
- klippy/configfile.py
- test/klippy/danger_options.cfg
Constants are defined in a `[constants]` section, and unused constants will only warn instead of erroring.
My intended usage looks like this:
```
[constants]
run_current_ab: 1.9
[tmc5160 stepper_x]
run_current: ${constants.run_current_ab}
[tmc5160 stepper_y]
run_current: ${constants.run_current_ab}
```
`${option}` references the current section
`${section.option}` looks up anywhere
interpolation occurs at most 10 times right now to avoid infinite loops
> Configuration reference interpolation

- docs/Config_Reference.md
The force_move docs are using the incorrect unicode for the "warning sign", making it show differently from the rest of the entries.
Here's the browser debug showing the problem:
> Fix incorrect unicode in docs

- docs/Config_Reference.md
- klippy/extras/danger_options.py
- klippy/toolhead.py
When false, this prevents `toolhead` from logging every change to
velocity limits to klippy.log
Some slicers emit a ton of `SET_VELOCITY_LIMIT`s
> Add danger_option log_velocity_limit_changes

- docs/Status_Reference.md
- klippy/mcu.py
expose the non critical disconnection status to the get_status()
> mcu: expose non critical status

- scripts/spi_flash/fatfs_lib.py
- scripts/spi_flash/spi_flash.py
> Fix spi_flash.py

- klippy/kinematics/limited_cartesian.py
limited cartesian inherits cartesian, so dual carriage works just fine
> idex: enable dual carriage support for limited cartesian

- docs/Config_Reference.md
- klippy/extras/temperature_fan.py
- test/klippy/curve_control.cfg
This pull request contains improvements to the code quality of the `ControlCurve` class to improve readability. Furthermore unnecessary operations were removed.
The current behaviour of the hysteresis when using a fan curve for control is incorrect and causes intermittent jumps between fixed pwm values without following the curve or reaching either end of the curve. This pull request contains an improved implementation.
Please be aware that this requests testing is limited as I'm currently not able to validate the behaviour in a live environment! I am open to feedback.
> temperature_fan: Improved code quality of fan curve and fixed hysteresis

- config/sample-duet3-1lc.cfg
- docs/Config_Reference.md
- klippy/extras/lis2dw.py
- klippy/extras/lis3dh.py
- src/Kconfig
- src/ar100/gpio.h
- src/atsamd/i2c.c
- src/generic/gpio.h
- src/sensor_lis2dw.c
This adds support for the LIS3DH, see [#6715](https://github.com/Klipper3d/klipper/pull/6715) on Klipper. I haven't squashed these, but can if requested. As implied by the content of these commits, this targets supporting the accelerometer on the Duet3D 1LC.
> Support for LIS3DH

- klippy/compat.py
- klippy/extras/telemetry.py
- klippy/printer.py
I previously was simply generating aliases for any currently imported klippy modules. While this somewhat worked, it did not handle cases where a module was not imported until after patching completed.
This new hooking method provides two features:
1. Rewrite non-package imports, e.g. `import mcu` effectively becomes `import klippy.mcu as mcu`
2. Provide aliases in sys.modules to prevent double-execution of modules.
The second is especially important as `is` and `isinstance` checks will fail between two seperately imported copies of the same module.
> Rewrite `compat` patching to fix module double-execution

- klippy/compat.py
iamnotahippie reported breakage in HappyHare after PR #490 was merged. I did a bunch of investigation, and found that the `path` rewrite in the import aliasing was causing the imported modules to have the wrong internal package name, which caused subsequent relative imports to also look in the wrong place
This change fixes that, and with compat in place HappyHare now passes our `--import-test`
> Fix compat again

- docs/Config_Reference.md
- docs/Danger_Features.md
- klippy/extras/bed_mesh.py
- klippy/extras/probe.py
- test/klippy/z_tilt_ng.cfg
implement  `use_probe_xy_offsets` to qgl/ztilt/bedtilt and others
> probe: implement use_probe_xy_offsets

- README.md
Existing instructions don't actually work. Fetch is required.
> Add missing git fetch to README

- docs/_kalico/mkdocs-requirements.txt
- docs/_kalico/mkdocs.yml
At the moment admonition blocks in the docs are rendered like 
This PR should fix them using a plugin, and rendering them mostly as they are on github.
> Fixing admonitions blocks on docs

- docs/MPC.md
- klippy/extras/control_mpc.py
docs and code had a discrepancy which is now fixed
also removed some redundant code
> updated docs to reflect actual mpc behaviour

- klippy/extras/telemetry.py
Telemetry commands were available while klipper wasnt ready, which should not be since they call for SAVE_CONFIG which is not available in that state
> Fix telemetry commands being available when they shouldnt

- docs/Config_Reference.md
Specifying the sense resistor as "motor" dependant confuses people as it is a driver spec, not a motor spec.
> fix sense_resistor description

- klippy/extras/ringing_test.py
The bleeding-edge-v2 ringing test by Dmitri wasn't working, so I fixed the issue by replacing the references to max_accel_to_decel to the new minimum_cruise_ratio and adjusting what it was set to.
> Update ringing test to use cruise ratio

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/tmc2240.py
- test/klippy/tmc.cfg
tmc2240 still had a default value for rref which should be removed since we removed sense_resistor default as well. Adjusted code and updated docs and tests accordingly
> removed tmc2240 default value

- docs/Config_Reference.md
Just added a note in the constants section of the documents to advise people they must always be lower case.
It caught me out, so I thought it might be worth adding it to the docs to save others.
- [N/A] added a test case if possible
- [N/A] if new feature, added to the readme
> Minor amend to documentation on constants

- docs/Config_Reference.md
- klippy/extras/tmc2240.py
The chip has a default value of 0, corresponding to 100V/µs. The default is overridden with 2 here, corresponding to 400V/µs to approximately match the TMC2209. This should also solve some overheating issues as it lowers the power dissipation at a 50kHz chopper frequency by around 1W.
This is currently untested.
> Expose slope_control field on TMC2240.

- docs/Config_Reference.md
- klippy/extras/resonance_tester.py
- klippy/extras/shaper_calibrate.py
added https://github.com/Klipper3d/klipper/pull/6723
> Added sweeping resonances

- docs/Axis_Twist_Compensation.md
- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/axis_twist_compensation.py
added https://github.com/Klipper3d/klipper/pull/6624 , without automatic_compensation
> Adds Y Axis Twist Compensation

- docs/Migrating_from_Klipper.md
Before being able to switch to kalico/main branch, git fetch is required to download the refs.
> fix: Fix missing command on migration from klipper

- klippy/extras/control_mpc.py
The docs state that for heater_bed the default target when calibrating mpc is 90 but the code just always uses 200, this fixes that
> Fix default target temp for mpc calibrate on bed

- docs/Config_Reference.md
- klippy/extras/duplicate_pin_override.py
- test/klippy/duplicate_pin_override.cfg
- test/klippy/duplicate_pin_override.test
As suggested via Discord ([here](https://discord.com/channels/1297243471442214913/1325807514222067774)), a quick feature to allow multiple instances of `duplicate_pin_override`
> feat: allow multiple instances of duplicate_pin_override

- docs/Config_Reference.md
- klippy/extras/danger_options.py
- klippy/kinematics/extruder.py
Following the idea from https://github.com/KalicoCrew/kalico/pull/489 allows control of pressure_advance logging. OrcaSlicer and its adaptative pressure advance emit many pressure advance changes.
> danger_options: adds the log_pressure_advance_changes option

- docs/Config_Reference.md
PID-Profile syntax was never added to the config reference as it is normally expected to be auto generated but there are use-cases where it is good to define one manually
> Added PID-Profile to config reference

- klippy/extras/tmc.py
- klippy/mcu.py
- klippy/msgproto.py
- pyproject.toml
- scripts/flash_usb.py
This can be a particularly painful source of bugs.[^1]  The objects are constructed and retain their state between calls.  It's best to avoid this pattern altogether.
[^1]: https://docs.astral.sh/ruff/rules/mutable-argument-default/
> Remove mutable parameter defaults

- docs/G-Codes.md
- klippy/toolhead.py
if max_x_velocity, max_x_accel and so on are available, they are available in command as well
> Enhance SET_VELOCITY_LIMIT

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/stepper.py
As suggested in https://github.com/KalicoCrew/kalico/issues/542 and per experience, matching homing_speed and second_homing_speed when homing using sensorless makes sense. Our own FAC (frequently asked configs) already recommends that.
> stepper: default second_homing_speed to homing_speed for sensorless

- docs/Config_Reference.md
- docs/G-Codes.md
- klippy/extras/probe.py
- bugfix for the last z lift movement after probing points. It should use `lift_speed`, and it was using `speed.`
- introduce a new parameter, `enforce_lift_speed`, to allow the user to decide whether to use the lift_speed or speed for the first movement to reach `horizontal_move_z.`
> qgl/ztilt - bugfix lift_speed and adds enforce_lift_speed

- README.md
- docs/Config_Changes.md
- docs/Config_Reference.md
- docs/Kalico_Additions.md
- klippy/extras/tmc.py
- klippy/extras/tmc2240.py
- test/klippy/tmc.cfg
Implemented adjustable CS and CR for tmc2240 as well as cleaning up the code and letting the superclass handle most of the initialization
> tmc2240: adjustable current scaler and current range

- lib/README
- lib/can2040/can2040.c
This provides improved support on rp2350 chips.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6776
> lib: Update can2040 to v1.7.0

- docs/Config_Reference.md
The tmc2240 current_range is a 2 bit field, so valid values are 0, 1, 2 and 3, not 0 and 32-255
> docs: fixes tmc2240 current_range documentation

- klippy/extras/garbage_collection.py
- klippy/toolhead.py
This significantly reduces the amount of data in the generation 2 garbage collection bucket from the initial startup of klipper.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6794
> garbage_collection: freeze objects on klippy ready (#6794)

- klippy/kinematics/extruder.py
As reported in https://github.com/KalicoCrew/kalico/issues/528, an extruder doesn't always have a stepper. This PR basically moves `per_move_pressure_advance` and validates the existence of an `extruder_stepper` to consume it.
> bugfix: move per_move_pressure_advance to extruder_stepper

- docs/Config_Reference.md
- klippy/extras/homing.py
- klippy/stepper.py
- klippy/toolhead.py
- test/klippy/tmc.cfg
As suggested in https://github.com/KalicoCrew/kalico/issues/395, untested yet
I also took the opportunity to rename `_set_current_homing` to `_set_homing_current` to match the new method added and make it more readable.
> homing: allow homing_accel to be configurable

- klippy/mcu.py
If the last restart was a `firmware_restart`, non critical mcus would fail to reconnect if they lost communication but not power (meaning they already have a config)
Instead of only trusting that they have the correct config, lets store the crc when the config is generated and compare with the crc from the mcu.
> bugfix: validate if non crit mcus are reconnecting with config

- docs/Status_Reference.md
- klippy/extras/canbus_stats.py
- klippy/mcu.py
- src/atsam/fdcan.c
- src/atsamd/fdcan.c
- src/generic/canbus.h
- src/generic/canserial.c
- src/generic/usb_canbus.c
- src/rp2040/can.c
- src/stm32/can.c
- src/stm32/fdcan.c
This PR adds support for reporting the micro-controller canbus receive and transmit error status.
The low-level canbus hardware will generally automatically retransmit messages that don't transmit correctly (eg, due to line noise). Unfortunately, this system may hide wiring problems - wiring problems that could cause hard to debug failures in the middle of a print.
The new code here will report the low-level interface statistics in the log statistics messages. For example, one might see messages like: Stats 815.9: ... canstat_mcu: rx_error=0 tx_error=0 bus_state=active ... canstat_corexy_rear_left: rx_error=0 tx_error=0 bus_state=active
In addition to the additional logging, the "usb to canbus bridge mode" has also been extended to detect canbus stalls. Previously, if the canbus were to …
> Improved canbus diagnostics (#6784)

- klippy/extras/probe.py
Many people coming from Klipper will have `METHOD=rapid_scan` in their start print macros for bed mesh and such. This ends up being treated as `manual` by Kalico, leading to a confusing manual Z probe during print start. This just treats `rapid_scan` as `automatic` for convenience/compatibility until rapid scan gets implemented.
> Treat rapid_scan probe method as automatic

- klippy/extras/axis_twist_compensation.py
Fixes https://github.com/KalicoCrew/kalico/issues/587!
This PR replaces `all()` with `is None` in the axis twist compensation guards in the `AXIS_TWIST_COMPENSATION_CALIBRATE` command handler.  This fixes a bug were 0 coordinate values in `[axis_twist_compensation]` unexpectedly makes `AXIS_TWIST_COMPENSATION_CALIBRATE` return this error:
>   AXIS_TWIST_COMPENSATION for X axis requires
>   calibrate_start_x, calibrate_end_x and calibrate_y
>   to be defined
I should add that there are no current tests for `cmd_AXIS_TWIST_COMPENSATION_CALIBRATE`, so I didn't add any tests to ensure this behavior in this PR.
From https://github.com/KalicoCrew/kalico/issues/587:
> When calibrate_start_x, calibrate_end_x, or calibrate_y is set to 0, like so (see [the config …
> Fix 0 coordinates raising error in axis twist compensation

- README.md
Fix Danger Additions link, change to proper link. If you click on the link it redirects to the Kalico Additions link, so might as well.
> Update Danger Features link to Kalico Additions

- .github/pull_request_template.md
Fixes https://github.com/KalicoCrew/kalico/issues/584!
This PR removes the "squashed to 1 commit" PR template checklist item.  The squash merge strategy is configured for this repository, so this checklist item is obsolete :+1: 
From https://github.com/KalicoCrew/kalico/issues/584:
> This is in the PR template:
> 
> https://github.com/KalicoCrew/kalico/blob/aa4cc80507a985b33de8b037cb8e400e7e168201/.github/pull_request_template.md?plain=1#L3-L9
> 
> I was curious about the `- [ ] squashed to 1 commit` checklist item, and asked about this in the Kalico Discord server.  This is what was said:
> 
> > It is just a suggestion, and from a time where squash commits weren’t enabled
> > but mostly because I like the commit history looking nice and clean without 10x ‘fix fix fix’ 
> 
> This …
> Remove "squashed to 1 commit" PR template checklist item

- config/generic-bigtreetech-skr-mini-e3-v3.0.cfg
Related to https://github.com/KalicoCrew/kalico/issues/582.
From [the Voron bigtreetech-skr-mini-e3-v3.0.cfg file](https://github.com/VoronDesign/Voron-0/blob/a53fc87562fd630c846af38d7de850c894dc3d85/Firmware/bigtreetech-skr-mini-e3-v3.0.cfg#L65-L75):
```ini
[tmc2209 stepper_x]
uart_pin: PC11
tx_pin: PC10
uart_address: 0
interpolate: False
sense_resistor: 0.110
stealthchop_threshold: 0                                            # Set to 999999 to turn stealthchop on, and 0 to use spreadcycle
diag_pin: ^PC0  													# YOU NEED TO JUMP THIS DIAG PIN ON YOUR BOARD FOR SENSORLESS HOMING TO WORK 
driver_SGTHRS: 255                                                  # this is set to 255 which is the MAX sensitivity for sensorless homing, you will need to tune this later
```
This PR copies …
> Add default 0.11 sense_resistor values for SKR Mini E3 V3.0 example config

- docs/Status_Reference.md
- klippy/extras/skew_correction.py
Added a command to retrieve the name of the current tilt correction configuration.
In some cases (such as enabling filament cutter or nozzle wipe), activating tilt correction may cause the tool head to exceed its range of motion. By retrieving the current tilt correction name, it is possible to get the tilt configuration name before execution, unload tilt correction, execute the command (cut filament or wipe nozzle), and then reload tilt correction using the obtained name.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6821
> skew_correction: Supports retrieving the name of the currently loaded skew correction

- scripts/spi_flash/board_defs.py
Addition to the board_defs file for the BTT Octopus Max EZ, written and confirmed by discord user Nikki @winningfaith81
Klipper PR: https://github.com/Klipper3d/klipper/pull/6817
> spi_flash: Update board_defs.py - BTT Octopus Max EZ (#6817)

- src/stm32/Kconfig
- src/stm32/stm32f0.c
This mcu has smaller memory and may require remapping of PA11/PA12.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6799
> stm32: Add support for stm32f070x6 mcus

- docs/Benchmarks.md
- docs/Features.md
- src/rp2040/main.c
- test/configs/rp2040.config
- test/configs/rp2350.config
RP2040 is now certified to run at 200Mhz clock instead of 133Mhz (125Mhz from SDK was used).
https://github.com/raspberrypi/pico-sdk/releases/tag/2.1.1
So, if no one minds, this is an overclock to the new allowed ones.
New perf values:
`arm-none-eabi-gcc (Arch Repository) 14.2.0`
```
rp2040	  ticks
1 stepper 3  ~ 4000K
3 stepper 14 ~ 2571K
```
Which allows us to place it aside with STM32F446 on the benchmark page.
This patch has been only tested on the development board.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6829
> RFC RP2040: set clock to 200Mhz

- docs/Config_Changes.md
- docs/Config_Reference.md
- klippy/extras/control_mpc.py
- klippy/extras/tmc5160.py
- test/klippy/tmc.cfg
The `driver_CS` parameter has been added to tmc5160. The ideal driver_cs value may be found by setting the CS value on the tmc5160_calculations.xlsx spreadsheet, under the chopper tab, so that the Rsense value in the spreadsheet matches `sense_resistor` as defined in printer.cfg. While it's not necessary to change the CS value, it can be helpful to reach adequate hystersis values on high current drivers paired with low current motors. The default for this value is 31, meaning only globalscaler will be used to scale the current during normal operation. Errors will be invoked if the CS value is set too low, as the target current will not be able to be reached.
Update tmc5160.py
> tmc5160: expose driver_CS, defaults to 31

- src/generic/usb_cdc.c
- src/generic/usb_cdc.h
- src/generic/usb_cdc_ep.h
- src/lpc176x/usb_cdc_ep.h
It seems the Linux kernel will consider a maximum size usb packet to be a transaction that will continue into the next usb packet.  It will thus hold on to the traffic from the first packet until it gets the next packet.  However, if the mcu has no further data to send after the first packet then the data could get delayed for an extended period of time.
To avoid this, check for transmissions that could end on a maximum sized packet and send that data in two packets instead.  This avoids this unusual corner case.
It's very rare for this exact sequence to occur (ending a series of messages on a 64 byte usb packet), which is why this has probably not been noticed before.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6811
> usb_cdc: Avoid ending a transmission with a max size usb packet

- src/sensor_ads1220.c
- src/sensor_hx71x.c
- src/sensor_ldc1612.c
As the input values are uint8_t types, any shift may result in value loss.
Explicit promotion to the output type (uint32_t) keeps things safe.
Have also changed the int32_t in ads1220_read_adc to uint32_t, type promotion and bit manipulation are a bit 'weird' on signed integers, so keep it as an unsigned to align with following function call parameter type.
Have retained the prior explicit sign extension logic however.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6665
> Warning Fix: Current code produces warnings for possible value overflows.

- README.md
- klippy/printer.py
- klippy/webhooks.py
Closes https://github.com/KalicoCrew/kalico/issues/604!
This PR adds three new options to klippy.py, as seen from this truncated help page:
```
--api-server-user=APISERVER_USER
api server unix domain socket user
--api-server-group=APISERVER_GROUP
api server unix domain socket group
--api-server-file-mode=APISERVER_FILE_MODE
api server unix domain socket file mode
```
These options allow user to change the user, group, and file mode of the API server socket, i.e. `/run/kalico/ud_sock`.
For example, these options...
```
/usr/bin/python /usr/lib/kalico/klippy/klippy.py \
/etc/kalico/kalico.cfg \
--input-tty=/run/kalico/sock \
--api-server=/run/kalico/ud_sock \
--api-server-group=tty \
--api-server-file-mode=660
```
...will create `/run/kalico/ud_sock` like so:
```
srw-rw---- 1 kalico tty …
```
> Add options to change mode, user, and group of API server socket

- src/Kconfig
- src/Makefile
replaces WANT_SENSORS with WANT_ADXL, WANT_THERMOCOUPLE, WANT_SENSOR_ANGLE and WANT_MPU9250
> kconfig: adds more flexibility small mcus

- README.md
- docs/Command_Templates.md
- docs/Kalico_Additions.md
- klippy/configfile.py
- klippy/extras/gcode_macro.py
- klippy/macro.pyi
- test/klippy/macro_loading.cfg
- test/klippy/macro_loading.test
- test/klippy/macro_loading/include.cfg
- test/klippy/macro_loading/macro.gcode.j2
- test/klippy/macro_loading/macro.py
Currently, writing a python macro is somewhat painful, requiring preficing each line with a single `!` to make preserve indentation. This also heavily limits editor support.
This PR adds support for `!!include path/to/macro.py` (and technically `!!include macro.notpy` resolves as jinja2 gcode templates).
For python macros, I've also added type stubs in `klippy/macro.pyi` and added `TYPE_CHECKING` to the environment. This allows for basic typing support in macro definitions. In the future I would love to be able to generate a bespoke type stub including Printer objects, but thats long term.
```
if TYPE_CHECKING:
from klippy.macro import *
```
> Support loading gcode_macro templates from files

- klippy/extras/pa_test.py
- klippy/extras/ringing_test.py
Dmitri's PA and ringing test towers don't start the fan, so the user has to manually start them once the brim is done. This is a major nuisance.
This change starts the fan at 50% once the brim is done, that should be a good starting value for most printers. (note, I have a 24v printer with a 12v fan so it won't overvolt that)
> turn fan to 50% in ringing and PA test tower generators

- klippy/extras/temperature_mcu.py
Pull request for this issue https://github.com/KalicoCrew/kalico/issues/610
Add support for gd32e230x MCU used in Creality and Sovol printers. Have been using it for a month without any issues.
Don't know why, but Ruff check keep failing for no reason.
- [v] pr title makes sense
- [v] if new feature, added to the readme
- [v] ci is happy and green
> Update temperature_mcu.py to support gd32e230x MCUs

- docs/Config_Reference.md
- klippy/extras/danger_options.py
- klippy/mcu.py
adds danger_options.single_mcu_trsync_timeout
> adds danger_options.single_mcu_trsync_timeout

- docs/Config_Reference.md
- klippy/extras/danger_options.py
Fixes https://github.com/KalicoCrew/kalico/issues/625
> bugfix - single_mcu_trsync_timeout defaults to 0.25

- README.md
- docs/G-Codes.md
- docs/Kalico_Additions.md
- klippy/extras/bed_mesh.py
- test/klippy/bed_mesh_check.cfg
- test/klippy/bed_mesh_check.test
This pull request introduces a new BED_MESH_CHECK command that allows users to validate their bed mesh against specific criteria. This feature helps identify potential issues with bed levelling before starting a print.
- New BED_MESH_CHECK command with two validation parameters:
- MAX_DEVIATION: Validates that the difference between the highest and lowest mesh points doesn't exceed the specified value
- MAX_SLOPE: Validates that the maximum slope between adjacent mesh points doesn't exceed the specified value (in mm/mm)
> bed_mesh - new BED_MESH_CHECK gcode command

- src/stm32/stm32g4.c
- src/stm32/stm32h7.c
based on from https://github.com/KalicoCrew/kalico/pull/581
enables 25mhz crystal for stm32g4
fixes stm32h7 build when internal crystal is used
> stm32g4/h7 - fix pll_base when using a 25mhz crystal

- docs/Config_Reference.md
I believe it got lost between merges
> docs - fix delta kinematics header

- klippy/mcu.py
This PR fixes an issue where using SET_PIN with a disconnected non-critical MCU would cause a NoneType error rather than providing a helpful message. Now it properly raises a command error with a clear message about the disconnected MCU.
> mcu: Fix SET_PIN error with disconnected non-critical MCUs

- klippy/extras/z_calibration.py
Don't ask me why, but I need a negative switch offset, and there is a issue on the original plugin for the same reason: https://github.com/protoloft/klipper_z_calibration/issues/152
Anyway it is aligned with "Our goal is to support features and behavior that could be "risky" if used incorrectly." :)
p.s.: Tested and running on my printer.
> Allow negative "switch_offset" for the auto Z offset

- scripts/console.py
Fixes `TypeError: initializer for ctype 'uint8_t *' must be a bytes or list or tuple, not str`
> console - encode the message before sending it

- src/stm32/i2c.c
Port of https://github.com/Klipper3d/klipper/pull/6876
> This configuration is used by the Prusa xBuddy board (an stm32f427, which is very close to the stm32f429) for its peripheral I2C port, which is where the Hackerboard (GPIO expansion board) is connected.
>
> There is one additional I2C configuration on the stm32f4x5 boards which is not yet included in the Klipper code, which looks like it's I2C3 on PA8 and PC9, but I'm unable to test that on my hardware.
- [~] added a test case if possible
- [~] if new feature, added to the readme
> stm32: Add support for additional i2c bus

- src/stm32/gpio.h
- src/stm32/hard_pwm.c
Port of https://github.com/Klipper3d/klipper/pull/6892
> The stm32 hard_pwm.c code implements a run-time division to calculate the cycle time. It's possible to avoid this division on the older chips by using a slightly different MAX_PWM value (257 instead of 255). The host python code should automatically adjust to that new value.
- [~] added a test case if possible
- [~] if new feature, added to the readme
> Avoid run-time division in stm32 hard_pwm code

- docs/Config_Reference.md
- docs/Dockable_Probe.md
- klippy/extras/dockable_probe.py
According this reports https://discord.com/channels/1297243471442214913/1297243471442214918/1362423782463246366
Allow z position for insert and detach position when probe is used as z endstop #616 , Z movements could also be done by `pre/post_attach/detach_gcode`
fix a typo for #650  
complete doc for pre/post_gcodes
> Dockable_probe : Insert/detach z position, fix typo

- docs/Installation.md
Fixed typos, hyphenation, and minor phrasing for better readability.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6874
> docs: Fix typos in installation.md

- klippy/extras/axis_twist_compensation.py
axis_twist_compensation on klippy:connect state checks for the presence of the 'probe' object, but if it is missing, it causes an error in the 'PrinterConfig' object, which does not have such an attribute.
Klipper PR https://github.com/Klipper3d/klipper/pull/6881
> axis_twist_compensation: Fix AttributeError on klippy connect state

- README.md
Added additional instructions for KIAUH v4 and KIAUH v6 as v6 is not in full release yet. Due to changes in the KIAUH rewrite to v6, if you add the repos to your klipper_repos.txt copying from the latest readme update for using v4. You add an extra space between the repo link and branch to the .kiauh.ini after selecting the new repo and KIAUH will fail to load until that is corrected.
> docs: updated kiauh steps for KIAUH v4 or v6

- docs/Config_Reference.md
- klippy/extras/tmc2130.py
- klippy/extras/tmc2208.py
- klippy/extras/tmc2209.py
This PR simply adds missing config options from TMC drivers.
The intended use is to define the default value.
This can then be used to passively brake the Z axis instead of disabling motors for printers where appropriate.
Example: Voron 2.4, probably some deltas.
[Discourse link with suggested macros](https://klipper.discourse.group/t/example-how-to-make-passive-breaking-work-for-z/22861)
Thanks.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6882
> tmc: add missing freewheel config options 2208/2209/2130

- docs/Config_Reference.md
- docs/Kalico_Additions.md
- klippy/extras/resonance_tester.py
This PR enhances the `resonance_tester` module to support multiple accelerometer chips in the configuration section while maintaining backward compatibility. It adds a new `accel_chips` parameter that accepts a comma-separated list of accelerometer chips.
The implementation maintains the existing behavior of combining data from all chips for resonance analysis and input shaper calibration, while ensuring that raw data files are properly labeled with chip names.
> Add support for multiple accelerometer chips in resonance_tester config

- .github/workflows/ci-build_test.yaml
- src/Makefile
Turns out all the ::group: bits are already there in the output, but docker
build is putting step numbers and timing in front. --progress=plain should
prevent that.
> Hack docker progress for ci builds so that ::group: is recognized

- src/rp2040/spi.c
Mellow FLY SHT36 Pro toolboard uses those pins
Klipper PR: https://github.com/Klipper3d/klipper/pull/6867
> rp2040: define spi bus on pins 12,11,10

- klippy/extras/bus.py
- scripts/spi_flash/spi_flash.py
- src/spi_software.c
Software SPI right now works as fast as it can.
That is fine, but it will be better if it respects the configured limit.
Should fix the too-fast RP2040: https://klipper.discourse.group/t/fly-sht36-pro-rp2040-spi/22586/4
Klipper PR:https://github.com/Klipper3d/klipper/pull/6856
> Software SPI: make it respect rate limits

- src/stm32/Kconfig
- src/stm32/serial.c
STM32F401 has USART6 on PA12/PA11 and PC7/PC6 with alternate function mapping AF08. This can be used, for example, to connect to the Elegoo Neptune 3, where PA12/PA11 are wired to an RJ10 plug going to the stock screen.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6830
> stm32: Add support for USART6 on STM32F401

- scripts/Dockerfile-build
- scripts/ci-build.sh
As per https://github.com/Klipper3d/klipper/pull/6887 the packages removed in this PR were only used to build pru gcc and we have removed that from the ci long time ago.
> docker image: remove unused packages

- src/generic/usb_canbus.c
There was a small race condition that could allow transmit "echo" frames to become briefly stalled when in USB to CAN bridge mode. This would likely only effect some controllers - potentially the stm32 usbotg (stm32f4 and stm32h7 devices).
The PR also contains a couple of commits intended to better organize the usb_canbus.c code.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6823
> Fix minor transmit stall race when in USB to CAN bridge mode

- scripts/check-software-div.sh
- scripts/ci-build.sh
- src/Kconfig
- src/atsamd/Kconfig
- src/hc32f460/Kconfig
- src/lcd_hd44780.c
- src/lcd_st7920.c
- src/neopixel.c
- src/rp2040/Kconfig
The older micro-controllers (AVR and cortex-m0) have to implement integer division in software. This software code is often bloated (600+ bytes of code) and can fill up the flash. With minor tweaks it is often possible to avoid using division.
The new build check introduced here will report a build error if any new run-time software divide operations are added to the AVR or STM32 code. This should help alert if a closer look at a change is needed.
This is based on top of https://github.com/Klipper3d/klipper/pull/6892 , as we need that fix to be able to verify the stm32 builds.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6893
> Add build test for unexpected run-time software divide

- docs/API_Server.md
- docs/Config_Reference.md
- docs/G-Codes.md
- docs/Load_Cell.md
- docs/Overview.md
- docs/Status_Reference.md
- docs/_kalico/mkdocs.yml
- klippy/extras/ads1220.py
- klippy/extras/hx71x.py
- klippy/extras/load_cell.py
This PR adds the features needed to make a load cell actually work as a gram scale. This PR will let you weight filament or measure a force in grams. (no homing or probing yet!)
- Convert raw sensor counts to grams and make this force data available via unix socket and printer object status
- Track sensor calibration state and allow sensors to go from un-calibrated to calibrated at runtime
- Add basic GCodes for tearing and reading the load cell
- Add a guided calibration tool so users can calibrate a load cell with a known mass or measured force.
- Add diagnostic GCode to check the health and performance of the load cell and sensor
Klipper PR: https://github.com/Klipper3d/klipper/pull/6729
> load_cell: Load cell gram scale

- klippy/extras/probe.py
The one in probe_points_helper doesn't match the PrinterProbe one, and it leads to
an exception if a caller does call it with gcmd. `z_tilt_ng` does this.
> Fix get_lift_speed signature in ProbePointsHelper

- docs/Nonlinear_Pressure_Advance.md
One user put NOZZLE = 235 where that should have been nozzle diameter
> Clarify parameters of PA test macro

- README.md
- src/linux/console.c
- src/linux/internal.h
- src/linux/main.c
This is in a a similar vein to #612, in that it allows for running the different components of klipper as different users, to limit damage should one of them misbehave or get pwned.
It adds two arguments to the `linux` host mcu, allowing the operator to set a group and mode for the pty that the mcu will create.
This was previously submitted to upstream as: https://github.com/Klipper3d/klipper/pull/6188
> Add options to change mode and group of linux mcu psuedoterminal

- klippy/extras/control_mpc.py
My printer has a printed frame and I don't want to subject it to heating the bed to 90C, so I tried reducing the minimum to 60C and it works fine.
> Reduce MPC minimum calibration temperature to 60C

- docs/Status_Reference.md
- klippy/extras/control_mpc.py
expose `filament_heat_capacity` and `filament_density` to for macros
these two vars are exposed to get current value for use in macros, useful in filament changer/mmu setups to prevent heating of the hotend during filament loads.
Existing macros exist to set these values from profiles or other methods, but all are preset and cannot be generically used.
example save/restore macro:
```ini
[gcode_macro Save_Filament_Heat]
description: Save the current filament heat value
variable_heatcap: -1
variable_dens: -1
gcode:
{% set heatcap = printer.extruder.control_stats.filament_heat_capacity %}
{% set dens = printer.extruder.control_stats.filament_density %}
{% if heatcap > 0 %}
MPC_SET HEATER=extruder FILAMENT_HEAT_CAPACITY=0 FILAMENT_DENSITY=0
SET_GCODE_VARIABLE MACRO=Save_Filament_Heat …
```
> add filament_heat_capacity and filament_density to exposed status variables in control_mpc.py

- src/neopixel.c
It looks like the solution for https://github.com/Klipper3d/klipper/pull/6873 is not merged, so the neopixel doesn't work on RP2040 boards (at least with the various BTT EBB boards and LEDs) in Kalico only, since this was fixed upstream last April with commit [5b2f810](https://github.com/Klipper3d/klipper/commit/5b2f8104c7106a2126949dcb0502dff5491023b2):
> The rp2040 operates at a fast internal clock with a relatively slow external timer and dividing down could result in a too small delay.
> Fix neopixel timing on RP2040 MCUs (merge from upstream)

- klippy/mcu.py
Previously the maximum value would just silently be limited, causing confusing out-of-range errors on MCUs that allow for a higher value. This is also useful for any users who have changed the default oversampling value to something higher.
This does not allow for the usage of MCUs with higher bit-depth ADCs, but it will at least save the next person from the confusion that I went through.
> Raise error if max ADC sample value exceeds 0xFFFF

- docs/Command_Templates.md
- docs/Config_Reference.md
- klippy/extras/delayed_gcode.py
The `[delayed_gcode]` macro should also have a _description_ documentation section like `[gcode_macro]`.
This PR adds the functionality and also updates the docs.
> fix(delayed_gcode): add description like gcode_macro

- scripts/spi_flash/spi_flash.py
Fixes abc76ee963d4154dce0bd56f2fdb946d5065cc86.
Klipper PR [#6906](https://github.com/Klipper3d/klipper/pull/6906)
> spi_flash: fix spi bus switch (#6906)
