KalicoCrew/kalico

README.md

pending #26 and #43 to be merged

add dangerous features to readme

---

.github/workflows/ci-build_test.yaml
scripts/Dockerfile-build
scripts/ci-build.sh
scripts/ci-install.sh
test/configs/atmega328.config

needs https://github.com/DangerKlippers/danger-klipper/pull/55 first so tests can pass

tests on push; improve the docker image

---

docs/Config_Reference.md
docs/G-Codes.md
klippy/extras/probe.py
klippy/extras/z_tilt.py

https://github.com/Klipper3d/klipper/pull/4083
too many conflicts, so I reimplemented

sensille's z-tilt calibration

---

.github/workflows/ci-build_test.yaml
.github/workflows/ci-static_analysis.yaml
.github/workflows/klipper3d-deploy.yaml
.github/workflows/upstream-sync.yaml
README.md
test/klippy/z_calibration.cfg
test/klippy/z_calibration.test

readme and tests for z_calibration

---

scripts/spi_flash/board_defs.py
scripts/spi_flash/fatfs_lib.py

somehow, we lost these 2 defs when syncing with the upstream
this also fixes the chelper import in fatfs_lib.py

resync board_defs.py and fix chelper import

---

klippy/klippy.py

breathes life back into https://github.com/Klipper3d/klipper/pull/5470

revert kevin mcu protocol message change

---

.github/workflows/ci-build_test.yaml
.github/workflows/ci-builder.yaml
.github/workflows/ci-static_analysis.yaml
.github/workflows/klipper3d-deploy.yaml

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes

changes the default timeout to test and build jobs

---

klippy/extras/heaters.py

I don't know if it's a good idea ^^. Allow PID_V parameter to be modify whithout reloading too

Modify PID_V params without restart

---

README.md
docs/Config_Reference.md
docs/G-Codes.md
klippy/extras/z_tilt.py
klippy/extras/z_tilt_ng.py
test/klippy/z_tilt_ng.cfg
test/klippy/z_tilt_ng.test

the new z_tilt enforces >=3 points and we don't want to break 2 point tilt adjust

split upstream z_tilt and sensille's z-tilt

---

README.md
docs/G-Codes.md
klippy/extras/adxl345.py

Improves `ACCELEROMETER_QUERY` to be more useful for determining especially toolhead tilt.

adxl345: improve ACCELEROMETER_QUERY command

---

klippy/stepper.py

https://github.com/DangerKlippers/danger-klipper/issues/137

stepper: endstop_pin should be optional

---

config/printer-anycubic-kobra-plus-2022.cfg
config/printer-geeetech-301-2019.cfg
config/printer-modix-big60-2020.cfg
docs/Bed_Mesh.md
docs/Config_Changes.md
docs/Config_Reference.md
docs/G-Codes.md
docs/Measuring_Resonances.md
docs/Probe_Calibrate.md
docs/Skew_Correction.md
klippy/extras/bed_mesh.py
klippy/extras/heaters.py
klippy/extras/resonance_tester.py
klippy/extras/shaper_calibrate.py
klippy/extras/temperature_sensors.cfg
klippy/kinematics/extruder.py
scripts/calibrate_shaper.py
src/avr/Kconfig

Do not merge from Github, fast-forward locally once the PR is approved.

update to latest Klipper3d/klipper (31de734)

---

README.md
klippy/extras/gcode_macro.py

https://github.com/Klipper3d/klipper/pull/4072

expose math functions to gcode macros by mental

---

klippy/extras/adxl345.py
klippy/extras/angle.py
klippy/extras/bus.py
klippy/extras/lis2dw.py
klippy/extras/mcp4018.py
klippy/extras/samd_sercom.py
klippy/extras/tmc_uart.py
klippy/mcu.py
klippy/serialhdl.py

This reverts commit 88d62487f03d2539b0e16ccd6d93a7a3f444d758.

Revert "move add_config_cmd calls to config callback across all extras (#142)"

---

docs/Config_Reference.md
klippy/extras/screws_tilt_adjust.py

Pretty self explanatory, adds a new screw size. for reasons.

add m8 cw and ccw to screw tilt

---

klippy/extras/heaters.py

Fix small error for pid_profiles

---

klippy/extras/temperature_mcu.py

Fix missing mcu temperature

---

klippy/gcode.py

Fix for CANCEL_PRINT issues

---

klippy/extras/resonance_tester.py

hotfix: replace max_accel_to_decel by minimum_cruise_ratio

---

klippy/chelper/integrate.c
klippy/chelper/integrate.h
klippy/chelper/kin_extruder.c
klippy/chelper/kin_shaper.c

pressure advance: do not smooth base extruder position, only advance

---

test/klippy/belay.cfg
test/klippy/belay.test

This adds a test case for belay.

belay: add test case

---

klippy/extras/tmc2130.py
klippy/extras/tmc2240.py
klippy/extras/tmc2660.py
klippy/extras/tmc5160.py

Fixed homing_current

---

test/klippy/trad_rack.cfg
test/klippy/trad_rack.test

This adds a test case for trad_rack.

trad_rack: add test case

---

.github/CODEOWNERS

adds a CODEOWNERS file for auto review request

---

klippy/extras/dockable_probe.py

Fix this https://github.com/DangerKlippers/danger-klipper/issues/229
+fix z issue while probe_attach

Add activate/deactivate_gcode to dockable_probe

---

README.md

Update README.md to clarify there are 3 install options

---

src/rp2040/Kconfig
src/rp2040/serial.c

Modified serial.c and Kconfig to dynamically select all possible UART combinations for RP2040
Klipper PR: https://github.com/Klipper3d/klipper/pull/6549

rp2040: Add kconfig options for rp2040 uart (#6549)

---

src/stm32/spi.c

Add new pin set for spi2 on stm32g0 chips
Klipper PR: https://github.com/Klipper3d/klipper/pull/6569

stm32:  Add new spi2 on stm32g0 chips (#6569)

---

docs/Config_Changes.md
docs/Config_Reference.md
klippy/extras/adc_temperature.py
klippy/extras/aht10.py
klippy/extras/bme280.py
klippy/extras/danger_options.py
klippy/extras/ds18b20.py
klippy/extras/htu21d.py
klippy/extras/lm75.py
klippy/extras/sht3x.py
klippy/extras/spi_temperature.py
klippy/extras/temperature_combined.py
klippy/extras/temperature_host.py
klippy/extras/temperature_mcu.py
klippy/mcu.py
klippy/serialhdl.py
src/linux/sensor_ds18b20.c
src/thermocouple.c
test/klippy/danger_options.cfg

- rename `adc_ignore_limits` to `temp_ignore_limits`
- implement the ignore limits validation to remaining sensors
- document missing log parameters

sensors: rework temp_ignore_limits

---

klippy/mcu.py

mcu: fix temp_ignore_limits

---

docs/_klipper3d/mkdocs-requirements.txt
docs/_klipper3d/mkdocs.yml

upgrade mkdocs, change google analytics

---

klippy/extras/control_mpc.py
klippy/extras/heaters.py
klippy/klippy.py

feature/mpc experimental to bleeding-edge-v2

---

docs/Config_Reference.md
docs/_klipper3d/mkdocs-requirements.txt
docs/_klipper3d/mkdocs.yml
klippy/extras/adxl345.py
klippy/extras/homing.py
klippy/extras/lis2dw.py
klippy/extras/mpu9250.py
klippy/extras/probe.py
klippy/extras/tmc.py
klippy/extras/tmc2130.py
klippy/extras/tmc2208.py
klippy/extras/tmc2209.py
klippy/extras/tmc2240.py
klippy/extras/tmc2660.py
klippy/extras/tmc5160.py

master to bleeding-edge-v2 (May 22)

---

klippy/extras/adxl345.py
klippy/extras/lis2dw.py
klippy/extras/mpu9250.py

Add a check whether the mcu for an accelerometer is connected and error out early if not.

Check whether an adxl mcu is connected

---

klippy/mcu.py
klippy/serialhdl.py

stuff left behind from cherry-picks

be-v2: smol fixes

---

docs/Config_Reference.md
klippy/extras/tmc.py
klippy/stepper.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6601

Minor tmc driver improvements (#6601)

---

README.md
docs/Config_Reference.md
docs/G-Codes.md
klippy/extras/heated_fan.py
test/klippy/heated_fan.cfg
test/klippy/heated_fan.test

A new klippy module to support heated part cooling fan.
tested by @levins-law

A new klippy module to support heated part cooling fan

---

docs/TMC_Drivers.md

Some conflicting information just confusing some users. This is just temporary until we get the sensorless tuning docs ready

Remove some sensorless info, add some info 

---

README.md
docs/CONTRIBUTING.md
docs/Config_Reference.md
docs/Contact.md
docs/Danger_Features.md
docs/README.md
docs/_klipper3d/mkdocs.yml
docs/index.md

some docs changes

---

README.md
docs/Config_Reference.md
docs/Danger_Features.md
klippy/extras/respond.py
klippy/klippy.py

enable [respond] by default

---

README.md
docs/Config_Reference.md
docs/Danger_Features.md
klippy/extras/exclude_object.py
klippy/extras/force_move.py
klippy/extras/respond.py
klippy/klippy.py

enable [exclude_object] by default

feat: enable [exclude_object] by default

---

docs/MPC.md

Fix typo in MPC.md

---

klippy/chelper/kin_shaper.c

Initial Klipper PR: https://github.com/Klipper3d/klipper/pull/6460
This is needed to enable future Shake&Tune features like motor resonance mitigation, which we've already experimented with a bit, and probably some other new stuff we haven't even thought of yet!

kin_shaper: update max pulse number

---

klippy/extras/resonance_tester.py

resonance_tester: use gcmd.get_float()

---

klippy/extras/tmc.py

bugfix/sensorless - gotta call it

---

klippy/clocksync.py
klippy/extras/bulk_sensor.py
klippy/extras/ldc1612.py
klippy/mcu.py
klippy/msgproto.py
scripts/buildcommands.py
src/command.c
src/command.h
src/pru/pru0.c
src/sensor_bulk.h
src/sensor_ldc1612.c

Klipper PR: https://github.com/Klipper3d/klipper/pull/6613

Support 2-byte message ids in host/mcu protocol (#6613)

---

src/atsam/Makefile
src/atsamd/Makefile
src/generic/armcm_link.lds.S
src/hc32f460/Makefile
src/lpc176x/Makefile
src/rp2040/Makefile
src/rp2040/rp2040_link.lds.S
src/stm32/Makefile

Klipper PR: https://github.com/Klipper3d/klipper/pull/6615

Fix build on recent arm gcc/newlibc versions (#6615)

---

klippy/extras/z_tilt.py
klippy/extras/z_tilt_ng.py

bugfix/z_tilt: check if retry_result is a number before converting

---

klippy/extras/bus.py
klippy/extras/sht3x.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6634

sht3x: use periodic report mode (#6634)

---

docs/Installation.md
docs/OctoPrint.md
docs/Overview.md
docs/_klipper3d/mkdocs.yml

Added links for Fluidd/Mainsail/Octoprint
Added references to overview.md and mkdocs.yml and spelling errors.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6650

docs: Update Installation.md (#6650)

---

klippy/serialhdl.py

I've added a None check to the SerialReader, as it was causing an issues when using the flash-sdcard.sh script as described in issue #361.

(#361) Added None check to SerialReader constructor

---

docs/MPC.md

Added the new dragon ace "high power" heater to the MPC power-temp chart

Add new Dragon Ace heater to MPC doc

---

klippy/extras/neopixel.py

don't send data to neopixel if not connected

---

docs/Bed_Level.md

as suggested here: https://github.com/Klipper3d/klipper/pull/6686

docs: fix Bed_Level.md typo

---

src/stm32/i2c.c
src/stm32/stm32f0_i2c.c

Klipper PR: https://github.com/Klipper3d/klipper/pull/6687

STM32: Check for NACK (#6687)

---

docs/Config_Reference.md
src/stm32/stm32f0_i2c.c
src/stm32/stm32g4.c

Klipper PR: https://github.com/Klipper3d/klipper/pull/6694

stm32: allow 400Khz in stm32f0_i2c.c (#6694)

---

src/rp2040/i2c.c

For now, RP2040 silently ignores any kind of errors, and we only try to catch them by timeout condition.
I did some tests, write can't be timeouted actually, at least with a disconnected device.
So, these are specific checks for NACK.
I did reproduce Start NACK/Start Read NACK by disconnecting SDA line from the device.
Write NACK has not been tested, I'm a little puzzled about how to reproduce write NACK.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6692

rp2040: Check for i2c NACK/Start NACK (#6692)

---

docs/Benchmarks.md
docs/Config_Reference.md
klippy/extras/heaters.py
scripts/whconsole.py

klipper commits to mainline

---

klippy/extras/z_thermal_adjust.py

Initialize reference temp at startup with temperature sensor value instead of 0.
Fix `# don't apply to extrude only moves or when disabled`, don't ignore z moves

Set z_thermal_adjust ref_temperature at startup

---

docs/Config_Changes.md
klippy/extras/fan.py

Add the missing upper limit to displayed fan speed 
fix PR https://github.com/DangerKlippers/danger-klipper/pull/428

Fix : Upper limit to exposed fan speed

---

test/klippy/gcode_python.cfg
test/klippy/gcode_python.test

testing for python gcode templates

gcode_macro: adds testing for python templates

---

klippy/extras/gcode_macro.py

This enables the use of `{% break %}` and `{% continue %}` in for loops
See https://jinja.palletsprojects.com/en/stable/templates/#loop-controls

Add jinja2's loopcontrols extension

---

docs/Config_Changes.md
klippy/gcode.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6749

gcode: Improve handling of extended g-code commands with '*;#' characters

---

klippy/extras/tmc2240.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6757

tmc2240: Correct maximum TMC2240 UART address. (#6757)

---

docs/Config_Reference.md
docs/G-Codes.md
docs/Status_Reference.md
klippy/extras/tools_calibrate.py

Sourced from https://github.com/viesturz/klipper-toolchanger and updated for versatility and ease of use
This adds support for multi-tool offset calibration using a 3d probe, such as https://github.com/zruncho3d/nudge or any of the available off the shelf CNC 3D Probes with a digital output.

Add tools_calibrate

---

docs/Z_Calibration.md
klippy/extras/control_mpc.py

docs: Celsius typo

---

.github/FUNDING.yml
docs/Sponsors.md

docs: update donation details

---

klippy/toolhead.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6747

toolhead: Fixed junction deviation calculation for straight segments (#6747)

---

docs/Config_Reference.md
docs/G-Codes.md

adds some documentation to z_tilt_ng

docs: z_tilt_ng description

---

klippy/configfile.py
klippy/gcode.py
klippy/mathutil.py

Let's not accept NaN. Its iN[s]aNity

Parse floats, but error on NaN

---

klippy/extras/telemetry.py

Enable relevant telemetry commands for enabled/disabled/unconfigured'

---

docs/Config_Reference.md
docs/G-Codes.md

Add a line to the Config and GCode reference explaining ⚠️

---

klippy/extras/temperature_mcu.py

This should fix the debug_read register issue with not connected non critical mcus

temperature_mcu: bugfix for non critical mcus

---

klippy/extras/pid_calibrate.py

Fixes typo in pid_calibrate.py

---

.gitignore

Added pycharms idea folder to the gitignore so people using pycharm wont accidentally commit IDE files

Added pycharm to the gitignore

---

.github/workflows/ci-lintformat.yaml

https://github.com/astral-sh/ruff-action/releases/tag/v3.0.0

ci: update ruff-action

---

lib/rp2040_flash/main.c

Klipper PR: https://github.com/Klipper3d/klipper/pull/6760

lib: fix rp2040_flash (#6760)

---

klippy/extras/z_tilt.py
klippy/extras/z_tilt_ng.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6766

bugfix/z_tilt[_ng]: return done when max retries is 0

---

klippy/extras/screws_tilt_adjust.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6791

screws_tilt_adjust: initialize status result as a dictionary

---

docs/Config_Reference.md
docs/Dockable_Probe.md
klippy/extras/dockable_probe.py

as suggested in https://github.com/KalicoCrew/kalico/issues/327, this PR adds more hooks to dockable probe

dockable_probe: pre|post_attach|detach hooks

---

docs/Config_Reference.md

docs: improve the tmc sense_resistor description

---

src/stm32/gpio.h
src/stm32/stm32h7_spi.c

Klipper PR: https://github.com/Klipper3d/klipper/pull/6801

stm32: h7 spi support reload mode & frequency

---

klippy/extras/heaters.py

Update the heating code to periodically check that the main thread is operating properly.  This is a mitigation for some rare cases where the main thread may lockup while the background heater updating code continues to run.  The goal is to detect these rare failures and disable future heater updates.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6777

heaters: Disable heater if it appears main thread has stopped updating

---

klippy/extras/bed_mesh.py

With the introduction of "scanning" probes it has
become common for configurations to generate a large number of points.  This can overwhelm both the log and the pty when new points are generated.
This patch limits the initial points logged to 50.  In addition points are no longer logged or pushed over the pty when the mesh configuration changes.
Klipper PR: https://github.com/Klipper3d/klipper/pull/6828

bed_mesh: reduce generated point logging

---

pyproject.toml
scripts/klippy-requirements.txt
uv.lock

requirements - adds setuptools for python > 3.12

---

klippy/extras/axis_twist_compensation.py

remove unused code

---

klippy/chelper/kin_extruder.c
klippy/extras/extruder_smoother.py
klippy/kinematics/extruder.py
test/klippy/extruders.cfg

manually cherry-picked from https://github.com/dmbutyugin/klipper/commit/a878784fbc01cd3a1c54a5ce0b32fb48c0f58a2a

extruder: rename linear_offset to nonlinear_offset

---

klippy/kinematics/hybrid_corexy.py
klippy/kinematics/hybrid_corexz.py

This PR enhances the hybrid_corexy and hybrid_corexz kinematics to properly support multiple steppers per rail in the X axis.

kinematics: add X multi-rail support to hybrid_corexy and hybrid_corexz

---

README.md
docs/Kalico_Additions.md
klippy/extras/resonance_tester.py

as discussed in https://github.com/KalicoCrew/kalico/issues/398, a warning will be displayed if there is a fan on.

resonance_tester - warning if any fan is on

---

docs/Telemetry.md
docs/_kalico/mkdocs.yml

New Telemetry documentation page to describe what Telemetry is, what it does and what data it sends to us.

docs - adds Telemetry.md

---

docs/Config_Reference.md

Docs didnt reflect code behaviour, this is fixed now

driver_CS: fix documentation to reflect actual code behaviour

---

README.md

Update KIAUH Install Instruction
It's now using the kiauh.cfg as base for the install script.

Update KIAUH Install Instruction for new KIAUH repository config

---

docs/Status_Reference.md
klippy/extras/hall_filament_width_sensor.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6861

hall_filament_width_sensor: Add filament switch values to status

---

docs/Config_Reference.md
docs/TMC_Drivers.md

Klipper ocmmit: https://github.com/Klipper3d/klipper/commit/a90110d9bab2ae1bf878fd0974fa3d8f128a38f8

docs: Note stealthchop_threshold doesn't impact sensorless homing

---

klippy/extras/gcode_macro.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6839

jinja2: Expand template syntax errors

---

klippy/extras/temperature_combined.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6769

temperature combined: handle temp monitors and I2C sensors

---

klippy/chelper/kin_shaper.c

Forward post_cb calls from itersolve to the original kinematics.
Klipper PR https://github.com/Klipper3d/klipper/pull/6846

input_shaper: Fix for polar kinematics

---

docs/Axis_Twist_Compensation.md

Klipper PR: https://github.com/Klipper3d/klipper/pull/6827

docs: fix markup in Axis_Twist_Compensation.md (#6827)

---

src/stm32/spi.c

Klipper PR https://github.com/Klipper3d/klipper/pull/6902

stm32: Add support for spi6 on stm32f42x chips

---

docs/Measuring_Resonances.md
klippy/extras/icm20948.py
src/Kconfig
src/Makefile
src/sensor_icm20948.c

Klipper PR https://github.com/Klipper3d/klipper/pull/6756

icm20948: Add support for ICM20948 accelerometer

---

klippy/extras/bus.py
src/i2c_software.c

Port of https://github.com/Klipper3d/klipper/pull/6872

i2c_software: allow freq adjust

---

docs/Config_Reference.md
klippy/extras/adxl345.py
klippy/extras/icm20948.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6868

Icm20948: Fix accelerometer readings, some changes

---

docs/Config_Changes.md
docs/G-Codes.md
klippy/extras/resonance_tester.py

Klipper PR: https://github.com/Klipper3d/klipper/pull/6726

resonance_tester: Fix selection of non-adxl345 chips

---

docs/Nonlinear_Pressure_Advance.md

I also fixed a typo that was bothering me.

Document nonlinear version of SET_PRESSURE_ADVANCE

---

docs/Config_Reference.md

Docs : precise [constants] shows error if unused.

---

scripts/canbus_query.py

Some minor quality of life improvements, as I was fighting with CAN:
- Make canbus_query not require an argument, and instead just query all interfaces if no argument is specified
- Print a nice message if an interface specified on the command line cannot be found instead of exception vomit

QOL: improve canbus_query.py

---

Makefile

This is just a small quality-of-life feature

Print memory usage data when building
